"""The Alkera chart profile: a strict, validated subset of Vega-Lite v6.

A chart is a declarative spec, data plus encodings, and the rows it describes
are often the customer's stored LLM output: maximally adversarial text that an
agent read before it wrote the spec. So the validator is an **allowlist
walker**, never a denylist. Every key at every level is admitted because a rule
here names it; an unknown key is a refusal, which is why a Vega-Lite feature we
never considered (``data.url``, an ``expr`` anywhere, a ``bind`` to an input
element, a ``labelExpr``) cannot arrive by being forgotten.

What the profile guarantees about an admitted spec:

* **Nothing in it fetches.** No ``url`` anywhere, no image mark, no ``href``
  channel, no ``$schema`` other than the Vega-Lite URLs the renderer ignores.
* **Its expressions read rows and nothing else.** A ``calculate``, a string
  ``filter`` and a condition's string ``test`` are parsed with vega-expression's
  grammar and admitted only when every name in them is a field of ``datum``, a
  constant or one of Vega's pure functions (see *Expressions* below). No
  ``expr`` or ``signal`` key, no ``labelExpr``. Colors match a CSS color
  grammar, formats are bounded pattern strings. The renderer still runs Vega
  with ``vega-interpreter`` and a loader that refuses every load; the profile
  is the first wall, not the only one.
* **It is bounded.** Rows, columns, cell sizes, views, layers and transforms
  all have ceilings, so a spec cannot be made expensive to validate or render.
* **It binds.** Every field an encoding, a transform or a predicate names is
  reported with its path, so a caller holding the data's columns can refuse a
  typo instead of drawing an empty figure (Vega-Lite drops it silently).

The profile is **extended by registration**: marks, encoding channels,
transforms, aggregate ops, time units and color schemes live in registries on
a :class:`Profile`, and :data:`PROFILE` is the default one. A v1 feature is a
``register_*`` call, never a new branch in the walker.

This module is deliberately self-contained: standard library only, Python 3.8
syntax and runtime (the ``alkera`` distribution's floor). That distribution ships a
byte-identical copy (``packages/alkera-py/alkera/chart/_profile.py``, regenerated by ``make
gen-chart-profile``) so a notebook validates exactly as the server does without
importing anything from Alkera's own environment.

Error messages name the offending **path** and the allowed vocabulary, never a
value: a value is the customer's data or column name, and an echoed value is
the injected string handed back.
"""

from __future__ import annotations

import json
import math
import re
from collections.abc import Callable, Iterable, Mapping, Sequence
from typing import Any, Tuple

PROFILE_VERSION = "1.1.0"

#: The ``$schema`` a spec gets when it names none.
VEGA_LITE_V6_SCHEMA = "https://vega.github.io/schema/vega-lite/v6.json"
#: The v5 spelling the portal's save dialog has always written; still admitted.
VEGA_LITE_V5_SCHEMA = "https://vega.github.io/schema/vega-lite/v5.json"
#: Every ``$schema`` admitted: the Vega-Lite v5 and v6 schema URLs, optionally
#: versioned the way Altair writes them (``v6.4.1.json``). The renderer never
#: fetches it; anything else is a URL with no reason to be there.
SCHEMA_PATTERN = re.compile(
    r"^https://vega\.github\.io/schema/vega-lite/v[56](\.\d{1,3}){0,2}\.json$"
)

#: MIME type of an Alkera chart in a notebook output or a chat part.
CHART_MIME = "application/vnd.alkera.chart+json"

# Ceilings. Each one is a promise to every reader that the spec is cheap.
MAX_INLINE_ROWS = 50_000
MAX_ROW_FIELDS = 256
MAX_CELL_CHARS = 4_096
MAX_FIELD_CHARS = 256
MAX_TEXT_CHARS = 1_000
MAX_DESCRIPTION_CHARS = 4_000
MAX_DIMENSION = 4_000
MAX_VIEWS = 24
MAX_LAYERS = 16
MAX_TRANSFORMS = 32
MAX_PARAMS = 8
MAX_NESTING = 4
MAX_DATASETS = 16
MAX_LIST = 64

#: Names Vega reserves for its own signals; a selection named one of these
#: would collide with the runtime rather than fail to validate there.
RESERVED_PARAM_NAMES = frozenset(
    {
        "autosize",
        "background",
        "cursor",
        "datum",
        "event",
        "height",
        "item",
        "padding",
        "parent",
        "unit",
        "width",
    }
)


class ChartSpecError(ValueError):
    """A spec fell outside the profile.

    ``path`` is where (``layer[1].encoding.x.field``), empty for the spec
    itself; the message names the path and the allowed vocabulary, never a
    value.
    """

    def __init__(self, message: str, path: str = "") -> None:
        super().__init__(message)
        self.path = path


def _label(path: str) -> str:
    return path or "a chart spec"


def _join(path: str, key: str) -> str:
    return f"{path}.{key}" if path else key


def _index(path: str, i: int) -> str:
    return f"{path}[{i}]"


class DataPolicy:
    """Where a spec's rows may come from.

    * ``inline``: ``data.values`` and named ``datasets`` carried in the spec.
    * ``host_tables``: ``data: {"name": ...}`` naming a table the host supplies
      (a result's rows, an Arrow attachment) rather than a dataset in the spec.
    * ``bound``: no data block at all; the host binds its one table (a saved
      result's rows) to the spec.
    """

    __slots__ = ("bound", "host_tables", "inline", "name")

    def __init__(self, name: str, *, inline: bool, host_tables: bool, bound: bool) -> None:
        self.name = name
        self.inline = inline
        self.host_tables = host_tables
        self.bound = bound

    def __repr__(self) -> str:
        return f"DataPolicy({self.name!r})"


#: A saved result's chart: the spec names columns, the result supplies rows.
BOUND = DataPolicy("bound", inline=False, host_tables=False, bound=True)
#: A notebook output, an agent's chart, an export: the rows travel in the spec.
INLINE = DataPolicy("inline", inline=True, host_tables=False, bound=True)
#: Inline rows plus named tables the host resolves (Arrow attachments, results).
HOSTED = DataPolicy("hosted", inline=True, host_tables=True, bound=True)


class _Walk:
    """What one validation pass learns on its way through a spec."""

    def __init__(self, profile: Profile, policy: DataPolicy) -> None:
        self.profile = profile
        self.policy = policy
        self.rows = 0
        self.views = 0
        self.depth = 0
        self.fields: list[tuple[str, str]] = []
        self.produced: set[str] = set()
        self.opaque_outputs = False
        self.params: dict[str, str] = {}
        self.param_refs: list[tuple[str, str]] = []
        self.dataset_names: set[str] = set()
        self.data_refs: list[tuple[str, str]] = []
        self.columns: set[str] = set()
        self.marks: set[str] = set()


# --------------------------------------------------------------------------
# Rules: each checks one value at one path and returns the admitted value.
# --------------------------------------------------------------------------


class Rule:
    """One allowlisted value shape. ``describe`` is what an author is told."""

    def check(self, value: object, path: str, walk: _Walk) -> object:
        raise NotImplementedError

    def describe(self) -> str:
        raise NotImplementedError


class Str(Rule):
    def __init__(
        self, max_chars: int = MAX_TEXT_CHARS, pattern: str | None = None, what: str = "string"
    ) -> None:
        self.max_chars = max_chars
        self.pattern = re.compile(pattern) if pattern else None
        self.what = what

    def check(self, value: object, path: str, walk: _Walk) -> object:
        if not isinstance(value, str):
            raise ChartSpecError(f"{_label(path)} must be a string", path)
        if len(value) > self.max_chars:
            raise ChartSpecError(
                f"{_label(path)} must be at most {self.max_chars} characters", path
            )
        if self.pattern is not None and not self.pattern.match(value):
            raise ChartSpecError(f"{_label(path)} is not an admitted {self.describe()}", path)
        return value

    def describe(self) -> str:
        return self.what


class Format(Str):
    """A d3-format or d3-time-format pattern: printable, no braces, bounded."""

    def __init__(self) -> None:
        super().__init__(64, r"^[^{}<>\\\x00-\x1f]*$")

    def describe(self) -> str:
        return "format pattern"


class Color(Str):
    """A CSS color literal: hex, a named color, or ``rgb()``/``hsl()`` with
    numeric arguments. Never ``url(...)``: an SVG paint server is a fetch."""

    def __init__(self) -> None:
        super().__init__(
            48,
            r"^(#[0-9a-fA-F]{3,8}|[a-zA-Z]{3,24}|"
            r"(rgb|rgba|hsl|hsla)\(\s*[0-9.%\s,/+-]{1,40}\))$",
        )

    def describe(self) -> str:
        return "color (hex, a named color, rgb() or hsl())"


class Num(Rule):
    def __init__(self, lo: float = -1e15, hi: float = 1e15, *, integer: bool = False) -> None:
        self.lo = lo
        self.hi = hi
        self.integer = integer

    def check(self, value: object, path: str, walk: _Walk) -> object:
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ChartSpecError(f"{_label(path)} must be a {self.describe()}", path)
        if self.integer and not isinstance(value, int):
            raise ChartSpecError(f"{_label(path)} must be an integer", path)
        if isinstance(value, float) and not math.isfinite(value):
            raise ChartSpecError(f"{_label(path)} must be a finite number", path)
        if not self.lo <= value <= self.hi:
            raise ChartSpecError(
                f"{_label(path)} must be between {_num(self.lo)} and {_num(self.hi)}", path
            )
        return value

    def describe(self) -> str:
        return "integer" if self.integer else "number"


def _num(value: float) -> str:
    return str(int(value)) if float(value).is_integer() else str(value)


class Bool(Rule):
    def check(self, value: object, path: str, walk: _Walk) -> object:
        if not isinstance(value, bool):
            raise ChartSpecError(f"{_label(path)} must be true or false", path)
        return value

    def describe(self) -> str:
        return "boolean"


class Null(Rule):
    def check(self, value: object, path: str, walk: _Walk) -> object:
        if value is not None:
            raise ChartSpecError(f"{_label(path)} must be null", path)
        return value

    def describe(self) -> str:
        return "null"


class Enum(Rule):
    def __init__(self, values: Iterable[str]) -> None:
        self.values = frozenset(values)

    def check(self, value: object, path: str, walk: _Walk) -> object:
        # Type first: ``in`` on a frozenset raises for an unhashable value, and
        # a nested object must be a refusal, never a crash a caller sees as 500.
        if not isinstance(value, str) or value not in self.values:
            raise ChartSpecError(f"{_label(path)} must be one of {sorted(self.values)}", path)
        return value

    def describe(self) -> str:
        return f"one of {sorted(self.values)}"


class Registry(Rule):
    """An enum whose members are a profile registry, read at check time so a
    registration made after the rule was built still counts."""

    def __init__(self, pick: Callable[[Profile], Iterable[str]], what: str) -> None:
        self.pick = pick
        self.what = what

    def check(self, value: object, path: str, walk: _Walk) -> object:
        allowed = frozenset(self.pick(walk.profile))
        if not isinstance(value, str) or value not in allowed:
            raise ChartSpecError(f"{_label(path)} must be one of {sorted(allowed)}", path)
        return value

    def describe(self) -> str:
        return self.what


class Field(Rule):
    """A field name a chart reads. Recorded with its path for binding."""

    def check(self, value: object, path: str, walk: _Walk) -> object:
        if not isinstance(value, str) or not value:
            raise ChartSpecError(f"{_label(path)} must be a non-empty string", path)
        if len(value) > MAX_FIELD_CHARS:
            raise ChartSpecError(
                f"{_label(path)} must be at most {MAX_FIELD_CHARS} characters", path
            )
        walk.fields.append((path, value))
        return value

    def describe(self) -> str:
        return "field name"


class Output(Rule):
    """A field name a transform creates (its ``as``)."""

    def check(self, value: object, path: str, walk: _Walk) -> object:
        if not isinstance(value, str) or not value or len(value) > MAX_FIELD_CHARS:
            raise ChartSpecError(
                f"{_label(path)} must be a non-empty string of at most "
                f"{MAX_FIELD_CHARS} characters",
                path,
            )
        walk.produced.add(value)
        return value

    def describe(self) -> str:
        return "output field name"


PARAM_NAME = r"^[A-Za-z_][A-Za-z0-9_]{0,63}$"


class ParamRef(Rule):
    """A reference to a selection the spec declares."""

    def check(self, value: object, path: str, walk: _Walk) -> object:
        if not isinstance(value, str) or not re.match(PARAM_NAME, value):
            raise ChartSpecError(f"{_label(path)} must name a declared selection", path)
        walk.param_refs.append((path, value))
        return value

    def describe(self) -> str:
        return "selection name"


class Const(Rule):
    def __init__(self, value: object) -> None:
        self.value = value

    def check(self, value: object, path: str, walk: _Walk) -> object:
        if value != self.value or type(value) is not type(self.value):
            raise ChartSpecError(f"{_label(path)} must be {json.dumps(self.value)}", path)
        return value

    def describe(self) -> str:
        return json.dumps(self.value)


class Arr(Rule):
    def __init__(self, item: Rule, *, max_items: int = MAX_LIST, min_items: int = 0) -> None:
        self.item = item
        self.max_items = max_items
        self.min_items = min_items

    def check(self, value: object, path: str, walk: _Walk) -> object:
        if not isinstance(value, list):
            raise ChartSpecError(f"{_label(path)} must be a list", path)
        if not self.min_items <= len(value) <= self.max_items:
            raise ChartSpecError(
                f"{_label(path)} must hold between {self.min_items} and {self.max_items} items",
                path,
            )
        return [self.item.check(item, _index(path, i), walk) for i, item in enumerate(value)]

    def describe(self) -> str:
        return f"list of {self.item.describe()}"


class Obj(Rule):
    """An object whose keys are exactly a subset of ``fields``."""

    def __init__(
        self,
        fields: Mapping[str, Rule],
        *,
        required: Sequence[str] = (),
        what: str = "object",
    ) -> None:
        self.fields = dict(fields)
        self.required = tuple(required)
        self.what = what

    def check(self, value: object, path: str, walk: _Walk) -> object:
        raw = _mapping(value, path)
        unknown = sorted(set(raw) - set(self.fields))
        if unknown:
            raise ChartSpecError(f"{_label(path)} carries unsupported keys: {unknown}", path)
        for key in self.required:
            if key not in raw:
                raise ChartSpecError(f"{_label(path)} must name {key}", _join(path, key))
        # Checked in the rule's order, so which refusal a spec earns does not
        # depend on how its writer happened to order its keys.
        checked = {
            key: self.fields[key].check(raw[key], _join(path, key), walk)
            for key in self.fields
            if key in raw
        }
        return {key: checked[key] for key in raw}

    def describe(self) -> str:
        return self.what


class OneOf(Rule):
    """The first alternative that admits the value. Alternatives are chosen
    by the value's JSON type so the refusal is the matching branch's own."""

    def __init__(self, *rules: Rule) -> None:
        self.rules = rules

    def check(self, value: object, path: str, walk: _Walk) -> object:
        kind = _json_kind(value)
        matching = [rule for rule in self.rules if kind in _accepts(rule)]
        if not matching:
            raise ChartSpecError(
                f"{_label(path)} must be {' or '.join(r.describe() for r in self.rules)}", path
            )
        if len(matching) == 1:
            return matching[0].check(value, path, walk)
        if isinstance(value, Mapping):
            # An object alternative whose required keys the value carries is
            # the one its writer meant, so its refusal is the one reported.
            keys = set(value)
            matching.sort(
                key=lambda r: not (isinstance(r, Obj) and r.required and set(r.required) <= keys)
            )
        first: ChartSpecError | None = None
        for rule in matching:
            trial = _Walk(walk.profile, walk.policy)
            try:
                rule.check(value, path, trial)
            except ChartSpecError as exc:
                first = first or exc
                continue
            return rule.check(value, path, walk)
        assert first is not None
        raise first

    def describe(self) -> str:
        return " or ".join(rule.describe() for rule in self.rules)


class Lazy(Rule):
    """A rule built on first use, for the recursive shapes (predicates, views)."""

    def __init__(self, build: Callable[[], Rule], what: str) -> None:
        self.build = build
        self.what = what
        self._rule: Rule | None = None

    def check(self, value: object, path: str, walk: _Walk) -> object:
        if self._rule is None:
            self._rule = self.build()
        return self._rule.check(value, path, walk)

    def describe(self) -> str:
        return self.what


class Custom(Rule):
    """A rule with its own check function, for the shapes keyed by a registry
    (marks, channels, transforms, views)."""

    def __init__(
        self, fn: Callable[[object, str, _Walk], object], what: str, kinds: Iterable[str]
    ) -> None:
        self.fn = fn
        self.what = what
        self.kinds = frozenset(kinds)

    def check(self, value: object, path: str, walk: _Walk) -> object:
        return self.fn(value, path, walk)

    def describe(self) -> str:
        return self.what


def _json_kind(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, (int, float)):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        return "array"
    if isinstance(value, Mapping):
        return "object"
    return "other"


def _accepts(rule: Rule) -> frozenset[str]:
    if isinstance(rule, (Str, Field, Output, ParamRef, Enum, Registry, Expression)):
        return frozenset({"string"})
    if isinstance(rule, Num):
        return frozenset({"number"})
    if isinstance(rule, Bool):
        return frozenset({"boolean"})
    if isinstance(rule, Null):
        return frozenset({"null"})
    if isinstance(rule, Const):
        return frozenset({_json_kind(rule.value)})
    if isinstance(rule, Arr):
        return frozenset({"array"})
    if isinstance(rule, Obj):
        return frozenset({"object"})
    if isinstance(rule, OneOf):
        out: set[str] = set()
        for inner in rule.rules:
            out |= _accepts(inner)
        return frozenset(out)
    if isinstance(rule, Custom):
        return rule.kinds
    return frozenset({"null", "boolean", "number", "string", "array", "object"})


def _mapping(value: object, path: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise ChartSpecError(f"{_label(path)} must be an object", path)
    for key in value:
        if not isinstance(key, str):
            raise ChartSpecError(f"{_label(path)} has a non-string key", path)
    return value


# --------------------------------------------------------------------------
# Registrations: what a mark, a channel and a transform are.
# --------------------------------------------------------------------------


class Transform:
    """One registered transform: the key that identifies it, the rule for its
    object, and the output fields it creates (``None``: it can create fields
    no static reading can name, so binding cannot be checked past it)."""

    def __init__(
        self,
        key: str,
        rule: Obj,
        outputs: Callable[[Mapping[str, Any]], Iterable[str] | None],
        note: str,
    ) -> None:
        self.key = key
        self.rule = rule
        self.outputs = outputs
        self.note = note


class Profile:
    """The registries a validation walks against.

    ``marks`` maps a mark name to the rule for the properties its object form
    may carry; ``channels`` maps an encoding channel to the rule for its
    definition; ``transforms`` maps the identifying key to a :class:`Transform`.
    """

    def __init__(self) -> None:
        self.marks: dict[str, dict[str, Rule]] = {}
        self.channels: dict[str, Rule] = {}
        self.transforms: dict[str, Transform] = {}
        self.aggregates: set[str] = set()
        self.time_units: set[str] = set()
        self.schemes: set[str] = set()
        self.interactions: dict[str, str] = {}
        self.expression_functions: set[str] = set()
        self.expression_constants: set[str] = set()

    def register_mark(self, name: str, props: Mapping[str, Rule]) -> None:
        self.marks[name] = dict(props)

    def register_channel(self, name: str, rule: Rule) -> None:
        self.channels[name] = rule

    def register_transform(self, transform: Transform) -> None:
        self.transforms[transform.key] = transform

    def summary(self) -> dict[str, Any]:
        """The vocabulary, for an author (a person reading docs, an agent
        reading its tool description)."""
        return {
            "profile": PROFILE_VERSION,
            "marks": sorted(self.marks),
            "channels": sorted(self.channels),
            "transforms": {key: t.note for key, t in sorted(self.transforms.items())},
            "aggregates": sorted(self.aggregates),
            "time_units": sorted(self.time_units),
            "schemes": sorted(self.schemes),
            "interactions": dict(sorted(self.interactions.items())),
            "expressions": {
                "functions": sorted(self.expression_functions),
                "constants": sorted(self.expression_constants),
                "reads": "datum.field or datum['field']",
            },
            "limits": {
                "inline_rows": MAX_INLINE_ROWS,
                "fields_per_row": MAX_ROW_FIELDS,
                "cell_chars": MAX_CELL_CHARS,
                "views": MAX_VIEWS,
                "layers": MAX_LAYERS,
                "transforms_per_view": MAX_TRANSFORMS,
                "dimension": MAX_DIMENSION,
                "expression_chars": MAX_EXPRESSION_CHARS,
                "expression_depth": MAX_EXPRESSION_DEPTH,
            },
        }


# Shared value shapes ---------------------------------------------------------

FIELD_TYPES = ("quantitative", "temporal", "ordinal", "nominal")
SCALAR = OneOf(Str(MAX_CELL_CHARS), Num(), Bool(), Null())
SHORT_TEXT = Str(MAX_TEXT_CHARS)
TITLE_TEXT = OneOf(Str(MAX_TEXT_CHARS), Arr(Str(MAX_TEXT_CHARS), max_items=4))
OPACITY = Num(0, 1)
PIXELS = Num(0, MAX_DIMENSION)
ANGLE = Num(-360, 360)
FONT_WEIGHT = OneOf(Enum({"normal", "bold", "lighter", "bolder"}), Num(100, 900, integer=True))
STROKE_DASH = Arr(Num(0, 1000), max_items=8)
SORT_ORDER = Enum({"ascending", "descending"})


def _aggregate_op() -> Rule:
    return OneOf(
        Registry(lambda p: p.aggregates, "aggregate op"),
        Obj({"argmin": Field()}, required=("argmin",), what="{argmin: field}"),
        Obj({"argmax": Field()}, required=("argmax",), what="{argmax: field}"),
    )


def _bin_params() -> Rule:
    return OneOf(
        Bool(),
        Obj(
            {
                "maxbins": Num(2, 1000, integer=True),
                "step": Num(1e-12, 1e15),
                "extent": Arr(Num(), min_items=2, max_items=2),
                "nice": Bool(),
                "binned": Bool(),
                "anchor": Num(),
                "minstep": Num(0, 1e15),
            },
            what="bin parameters",
        ),
    )


def _time_unit() -> Rule:
    return OneOf(
        Registry(lambda p: p.time_units, "time unit"),
        Obj(
            {
                "unit": Registry(lambda p: p.time_units, "time unit"),
                "utc": Bool(),
                "step": Num(1, 10_000, integer=True),
            },
            required=("unit",),
            what="time unit parameters",
        ),
    )


def _scale() -> Rule:
    return Obj(
        {
            "type": Enum(
                {
                    "linear",
                    "log",
                    "pow",
                    "sqrt",
                    "symlog",
                    "time",
                    "utc",
                    "ordinal",
                    "band",
                    "point",
                    "quantile",
                    "quantize",
                    "threshold",
                }
            ),
            "domain": OneOf(Arr(SCALAR, max_items=MAX_LIST), Const("unaggregated")),
            "domainMid": Num(),
            "range": OneOf(
                Arr(OneOf(Num(), Color()), max_items=MAX_LIST),
                Enum({"category", "ordinal", "ramp", "diverging", "heatmap"}),
            ),
            "scheme": Registry(lambda p: p.schemes, "color scheme"),
            "zero": Bool(),
            "nice": OneOf(Bool(), Num(1, 1000, integer=True)),
            "reverse": Bool(),
            "clamp": Bool(),
            "padding": Num(0, 1000),
            "paddingInner": Num(0, 1),
            "paddingOuter": Num(0, 10),
            "exponent": Num(-100, 100),
            "base": Num(0, 1000),
            "constant": Num(0, 1e15),
            "interpolate": Enum(
                {"rgb", "lab", "hcl", "hsl", "hsl-long", "hcl-long", "cubehelix", "cubehelix-long"}
            ),
        },
        what="scale",
    )


def _axis() -> Rule:
    return OneOf(
        Null(),
        Obj(
            {
                "title": OneOf(TITLE_TEXT, Null()),
                "format": Format(),
                "formatType": Enum({"number", "time", "utc"}),
                "labelAngle": ANGLE,
                "labelOverlap": OneOf(Bool(), Enum({"parity", "greedy"})),
                "labels": Bool(),
                "labelLimit": PIXELS,
                "grid": Bool(),
                "ticks": Bool(),
                "tickCount": Num(0, 1000, integer=True),
                "domain": Bool(),
                "orient": Enum({"top", "bottom", "left", "right"}),
                "values": Arr(SCALAR, max_items=MAX_LIST),
            },
            what="axis",
        ),
    )


def _legend() -> Rule:
    return OneOf(
        Null(),
        Obj(
            {
                "title": OneOf(TITLE_TEXT, Null()),
                "orient": Enum(
                    {
                        "left",
                        "right",
                        "top",
                        "bottom",
                        "top-left",
                        "top-right",
                        "bottom-left",
                        "bottom-right",
                        "none",
                    }
                ),
                "format": Format(),
                "formatType": Enum({"number", "time", "utc"}),
                "direction": Enum({"horizontal", "vertical"}),
                "columns": Num(0, 64, integer=True),
                "symbolType": Enum(
                    {
                        "circle",
                        "square",
                        "cross",
                        "diamond",
                        "triangle-up",
                        "triangle-down",
                        "stroke",
                    }
                ),
                "values": Arr(SCALAR, max_items=MAX_LIST),
                "labelLimit": PIXELS,
            },
            what="legend",
        ),
    )


def _header() -> Rule:
    return OneOf(
        Null(),
        Obj(
            {
                "title": OneOf(TITLE_TEXT, Null()),
                "labelAngle": ANGLE,
                "labelOrient": Enum({"top", "bottom", "left", "right"}),
                "format": Format(),
                "formatType": Enum({"number", "time", "utc"}),
                "labels": Bool(),
            },
            what="header",
        ),
    )


def _sort() -> Rule:
    return OneOf(
        Null(),
        SORT_ORDER,
        # An encoding sort: by another channel, "-" for descending.
        Enum(
            {
                "x",
                "y",
                "color",
                "size",
                "text",
                "-x",
                "-y",
                "-color",
                "-size",
                "-text",
                "opacity",
                "-opacity",
            }
        ),
        Arr(SCALAR, max_items=MAX_LIST * 4),
        Obj(
            {
                "field": Field(),
                "op": Registry(lambda p: p.aggregates, "aggregate op"),
                "order": OneOf(SORT_ORDER, Null()),
            },
            what="sort by field",
        ),
        Obj(
            {
                "encoding": Enum({"x", "y", "color", "size", "text", "opacity"}),
                "order": OneOf(SORT_ORDER, Null()),
            },
            what="sort by encoding",
        ),
    )


# Expressions -----------------------------------------------------------------
#
# Vega-Lite reads a string as an expression in places Altair writes every day:
# a ``calculate`` transform, a ``filter`` written as text (``transform_filter``
# with a string or an ``alt.datum`` comparison) and a condition's ``test``
# (``alt.condition`` and ``alt.when`` over ``alt.datum``). The renderer runs them
# with ``vega-interpreter`` over a parsed AST, never ``eval``, and its loader
# refuses every load, so an expression cannot fetch or generate code. What is
# left is what an expression may *read*, and that is decided here: a real
# tokenizer and parser for the grammar vega-expression accepts, then an
# allowlist over the tree. Admitted: literals (numbers, strings, booleans,
# null, arrays), fields of ``datum`` by name or by string key, the unary,
# binary, logical and ternary operators, Vega's constants, and Vega's pure
# functions. Refused: every other identifier (Vega would resolve it as a
# signal), member access on anything but ``datum`` (a numeric index into a
# value is the one exception), calls on anything but a function name, object
# and regular-expression literals, assignment, and any property name that
# reaches a prototype, in any spelling an escape can produce.
#
# ``now``, ``random`` and the ``sample*`` draws are admitted although they are
# not deterministic: they read the clock or a random source and nothing else,
# and Altair's jitter and "days since" recipes need them. Refused on purpose:
# ``regexp`` and ``test`` (a pattern can backtrack catastrophically on a
# customer's text), ``sequence``, ``timeSequence`` and ``utcSequence`` (they
# allocate without bound), ``merge`` and ``pluck`` (object assembly and field
# accessors), the data, scale, event, geo and tree functions (they reach the
# runtime's state), and the logging functions. ``pad`` allocates its length,
# so its length must be a number literal of at most ``MAX_PAD_LENGTH``.
#
# The renderer's guard (``packages/chart-guard/src/expression.ts``) implements the
# same grammar and the same allowlist; the shared corpus under
# ``packages/api-core/tests/fixtures/charts/profile/expressions`` holds both to
# it.

MAX_EXPRESSION_CHARS = 1_000
MAX_EXPRESSION_DEPTH = 32
MAX_EXPRESSION_ARGS = 8
MAX_PAD_LENGTH = 1_000

#: The named constants Vega defines (``Math.PI`` and the like).
EXPRESSION_CONSTANTS = frozenset(
    {
        "NaN",
        "E",
        "LN2",
        "LN10",
        "LOG2E",
        "LOG10E",
        "PI",
        "SQRT1_2",
        "SQRT2",
        "MIN_VALUE",
        "MAX_VALUE",
    }
)

#: Vega's expression functions that read only their arguments (and, for the
#: few named above, the clock or a random source).
EXPRESSION_FUNCTIONS = frozenset(
    {
        # control
        "if",
        # type checks and coercion
        "isArray",
        "isBoolean",
        "isDate",
        "isDefined",
        "isNumber",
        "isObject",
        "isRegExp",
        "isString",
        "isValid",
        "toBoolean",
        "toDate",
        "toNumber",
        "toString",
        # math
        "isNaN",
        "isFinite",
        "abs",
        "acos",
        "asin",
        "atan",
        "atan2",
        "ceil",
        "clamp",
        "cos",
        "exp",
        "floor",
        "hypot",
        "log",
        "max",
        "min",
        "pow",
        "random",
        "round",
        "sin",
        "sqrt",
        "tan",
        # statistics
        "cumulativeNormal",
        "cumulativeLogNormal",
        "cumulativeUniform",
        "densityNormal",
        "densityLogNormal",
        "densityUniform",
        "quantileNormal",
        "quantileLogNormal",
        "quantileUniform",
        "sampleNormal",
        "sampleLogNormal",
        "sampleUniform",
        # dates and times
        "now",
        "datetime",
        "date",
        "day",
        "dayofyear",
        "year",
        "quarter",
        "month",
        "week",
        "hours",
        "minutes",
        "seconds",
        "milliseconds",
        "time",
        "timezoneoffset",
        "timeOffset",
        "utc",
        "utcdate",
        "utcday",
        "utcdayofyear",
        "utcyear",
        "utcquarter",
        "utcmonth",
        "utcweek",
        "utchours",
        "utcminutes",
        "utcseconds",
        "utcmilliseconds",
        "utcOffset",
        # strings and arrays
        "length",
        "lower",
        "upper",
        "substring",
        "slice",
        "split",
        "join",
        "trim",
        "truncate",
        "replace",
        "pad",
        "indexof",
        "lastindexof",
        "reverse",
        "sort",
        "extent",
        "clampRange",
        "inrange",
        "lerp",
        "peek",
        "span",
        "parseFloat",
        "parseInt",
        # formatting and parsing
        "format",
        "timeFormat",
        "timeParse",
        "utcFormat",
        "utcParse",
        "monthFormat",
        "monthAbbrevFormat",
        "dayFormat",
        "dayAbbrevFormat",
        "timeUnitSpecifier",
    }
)

#: Property names that reach an object's prototype. Never a datum key and
#: never a string literal, however an escape spells them.
EXPRESSION_FORBIDDEN_NAMES = frozenset(
    {
        "__proto__",
        "constructor",
        "prototype",
        "__defineGetter__",
        "__defineSetter__",
        "__lookupGetter__",
        "__lookupSetter__",
    }
)

#: Functions Vega compiles with a fixed argument count.
_EXACT_ARITY = {"if": 3, "clamp": 3}

_PUNCTUATORS = (
    ">>>",
    "===",
    "!==",
    "<<",
    ">>",
    "<=",
    ">=",
    "==",
    "!=",
    "&&",
    "||",
    "++",
    "--",
    "+",
    "-",
    "*",
    "/",
    "%",
    "<",
    ">",
    "!",
    "~",
    "&",
    "|",
    "^",
    "?",
    ":",
    ",",
    ".",
    "(",
    ")",
    "[",
    "]",
)
_BINARY_PRECEDENCE = {
    "||": 1,
    "&&": 2,
    "|": 3,
    "^": 4,
    "&": 5,
    "==": 6,
    "!=": 6,
    "===": 6,
    "!==": 6,
    "<": 7,
    ">": 7,
    "<=": 7,
    ">=": 7,
    "<<": 8,
    ">>": 8,
    ">>>": 8,
    "+": 9,
    "-": 9,
    "*": 11,
    "/": 11,
    "%": 11,
}
_UNARY_OPERATORS = frozenset({"+", "-", "!", "~"})
_SIMPLE_ESCAPES = {
    "\\": "\\",
    "'": "'",
    '"': '"',
    "n": "\n",
    "r": "\r",
    "t": "\t",
    "b": "\b",
    "f": "\f",
    "v": "\v",
}
_DIGITS = frozenset("0123456789")
_HEX_DIGITS = frozenset("0123456789abcdefABCDEF")
_ID_START = frozenset("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_$")
_ID_PART = _ID_START | _DIGITS
_EXPRESSION_SPACE = frozenset(" \t\n\r\f\v")
_LINE_BREAKS = frozenset("\n\r\u2028\u2029")

_MALFORMED = "is not an expression the chart profile can read"


class ExpressionError(ValueError):
    """An expression outside the profile. The message is the reason, phrased
    to follow a path, and never repeats the expression."""


_Token = Tuple[str, Any]
_Node = Tuple[Any, ...]


def _scan_number(text: str, i: int) -> tuple[int, float]:
    n = len(text)
    if text.startswith(("0x", "0X"), i):
        j = i + 2
        while j < n and text[j] in _HEX_DIGITS:
            j += 1
        if j == i + 2:
            raise ExpressionError(_MALFORMED)
        value = float(int(text[i + 2 : j], 16))
    else:
        j = i
        while j < n and text[j] in _DIGITS:
            j += 1
        if j - i > 1 and text[i] == "0":
            # Vega reads a leading zero as an octal literal; nothing writes one.
            raise ExpressionError("writes a number with a leading zero")
        if j < n and text[j] == ".":
            j += 1
            while j < n and text[j] in _DIGITS:
                j += 1
        if j < n and text[j] in "eE":
            k = j + 1
            if k < n and text[k] in "+-":
                k += 1
            if k >= n or text[k] not in _DIGITS:
                raise ExpressionError(_MALFORMED)
            while k < n and text[k] in _DIGITS:
                k += 1
            j = k
        value = float(text[i:j])
    if j < n and text[j] in _ID_PART:
        raise ExpressionError(_MALFORMED)
    return j, value


def _scan_hex(text: str, i: int, count: int) -> int:
    digits = text[i : i + count]
    if len(digits) != count or any(ch not in _HEX_DIGITS for ch in digits):
        raise ExpressionError(_MALFORMED)
    return int(digits, 16)


def _scan_string(text: str, i: int) -> tuple[int, str]:
    quote = text[i]
    n = len(text)
    out: list[str] = []
    j = i + 1
    while True:
        if j >= n:
            raise ExpressionError(_MALFORMED)
        ch = text[j]
        if ch == quote:
            return j + 1, "".join(out)
        if ch in _LINE_BREAKS:
            raise ExpressionError(_MALFORMED)
        if ch != "\\":
            out.append(ch)
            j += 1
            continue
        j += 1
        if j >= n:
            raise ExpressionError(_MALFORMED)
        esc = text[j]
        if esc in _SIMPLE_ESCAPES:
            out.append(_SIMPLE_ESCAPES[esc])
            j += 1
        elif esc == "0" and not (j + 1 < n and text[j + 1] in _DIGITS):
            out.append("\0")
            j += 1
        elif esc == "x":
            out.append(chr(_scan_hex(text, j + 1, 2)))
            j += 3
        elif esc == "u" and j + 1 < n and text[j + 1] == "{":
            end = text.find("}", j + 2)
            digits = text[j + 2 : end] if end != -1 else ""
            if not 1 <= len(digits) <= 6 or any(c not in _HEX_DIGITS for c in digits):
                raise ExpressionError(_MALFORMED)
            code = int(digits, 16)
            if code > 0x10FFFF:
                raise ExpressionError(_MALFORMED)
            out.append(chr(code))
            j = end + 1
        elif esc == "u":
            out.append(chr(_scan_hex(text, j + 1, 4)))
            j += 5
        else:
            # Every other escape (octal, a line continuation, an identity
            # escape) is refused rather than decoded one way here and another
            # in the renderer.
            raise ExpressionError(_MALFORMED)


def _tokenize(text: str) -> list[_Token]:
    tokens: list[_Token] = []
    n = len(text)
    i = 0
    while i < n:
        ch = text[i]
        if ch in _EXPRESSION_SPACE:
            i += 1
        elif ch in _ID_START:
            j = i + 1
            while j < n and text[j] in _ID_PART:
                j += 1
            tokens.append(("id", text[i:j]))
            i = j
        elif ch in _DIGITS or (ch == "." and i + 1 < n and text[i + 1] in _DIGITS):
            i, number = _scan_number(text, i)
            tokens.append(("num", number))
        elif ch in "'\"":
            i, value = _scan_string(text, i)
            tokens.append(("str", value))
        else:
            for punctuator in _PUNCTUATORS:
                if text.startswith(punctuator, i):
                    tokens.append(("punc", punctuator))
                    i += len(punctuator)
                    break
            else:
                raise ExpressionError(_MALFORMED)
    tokens.append(("end", None))
    return tokens


class _ExpressionParser:
    """Recursive descent over vega-expression's grammar, to a tuple tree:
    ``("num", v)``, ``("str", v)``, ``("lit", v)``, ``("id", name)``,
    ``("member", object, property, computed)``, ``("call", name, args)``,
    ``("array", items)``, ``("unary", op, arg)``, ``("binary", op, l, r)``,
    ``("cond", test, yes, no)``."""

    def __init__(self, tokens: list[_Token]) -> None:
        self.tokens = tokens
        self.pos = 0
        self.depth = 0

    def _at(self, punctuator: str) -> bool:
        kind, value = self.tokens[self.pos]
        return kind == "punc" and value == punctuator

    def _expect(self, punctuator: str) -> None:
        if not self._at(punctuator):
            raise ExpressionError(_MALFORMED)
        self.pos += 1

    def _enter(self) -> None:
        self.depth += 1
        if self.depth > MAX_EXPRESSION_DEPTH:
            raise ExpressionError(f"nests deeper than {MAX_EXPRESSION_DEPTH} levels")

    def parse(self) -> _Node:
        node = self._conditional()
        if self.tokens[self.pos][0] != "end":
            raise ExpressionError(_MALFORMED)
        return node

    def _conditional(self) -> _Node:
        self._enter()
        node = self._binary(1)
        if self._at("?"):
            self.pos += 1
            yes = self._conditional()
            self._expect(":")
            no = self._conditional()
            node = ("cond", node, yes, no)
        self.depth -= 1
        return node

    def _binary(self, min_precedence: int) -> _Node:
        left = self._unary()
        while True:
            kind, value = self.tokens[self.pos]
            precedence = _BINARY_PRECEDENCE.get(value) if kind == "punc" else None
            if precedence is None or precedence < min_precedence:
                return left
            self.pos += 1
            right = self._binary(precedence + 1)
            left = ("binary", value, left, right)

    def _unary(self) -> _Node:
        kind, value = self.tokens[self.pos]
        if kind == "punc" and value in _UNARY_OPERATORS:
            self.pos += 1
            self._enter()
            argument = self._unary()
            self.depth -= 1
            return ("unary", value, argument)
        return self._postfix()

    def _list(self, close: str) -> list[_Node]:
        items: list[_Node] = []
        if self._at(close):
            self.pos += 1
            return items
        while True:
            items.append(self._conditional())
            if self._at(","):
                self.pos += 1
                continue
            self._expect(close)
            return items

    def _postfix(self) -> _Node:
        node = self._primary()
        while True:
            if self._at("."):
                self.pos += 1
                kind, value = self.tokens[self.pos]
                if kind != "id":
                    raise ExpressionError(_MALFORMED)
                self.pos += 1
                node = ("member", node, ("str", value), False)
            elif self._at("["):
                self.pos += 1
                prop = self._conditional()
                self._expect("]")
                node = ("member", node, prop, True)
            elif self._at("("):
                if node[0] != "id":
                    raise ExpressionError("calls something that is not a function name")
                self.pos += 1
                args = self._list(")")
                if len(args) > MAX_EXPRESSION_ARGS:
                    raise ExpressionError(
                        f"passes more than {MAX_EXPRESSION_ARGS} arguments to a function"
                    )
                node = ("call", node[1], args)
            else:
                return node

    def _primary(self) -> _Node:
        kind, value = self.tokens[self.pos]
        self.pos += 1
        if kind in ("num", "str"):
            return (kind, value)
        if kind == "id":
            if value in ("true", "false"):
                return ("lit", value == "true")
            if value == "null":
                return ("lit", None)
            return ("id", value)
        if kind == "punc" and value == "(":
            node = self._conditional()
            self._expect(")")
            return node
        if kind == "punc" and value == "[":
            items = self._list("]")
            if len(items) > MAX_LIST:
                raise ExpressionError(f"writes an array of more than {MAX_LIST} items")
            return ("array", items)
        raise ExpressionError(_MALFORMED)


def _is_index(node: _Node) -> bool:
    return node[0] == "num" and node[1] >= 0 and float(node[1]).is_integer()


def _check_expression_tree(root: _Node, profile: Profile) -> list[str]:
    fields: list[str] = []
    stack = [root]
    while stack:
        node = stack.pop()
        kind = node[0]
        if kind in ("num", "lit"):
            continue
        if kind == "str":
            if node[1] in EXPRESSION_FORBIDDEN_NAMES:
                raise ExpressionError("names a property no expression may read")
        elif kind == "id":
            if node[1] == "datum":
                raise ExpressionError("reads the whole row; read one field by name")
            if node[1] not in profile.expression_constants:
                raise ExpressionError("reads a name outside the expression allowlist")
        elif kind == "member":
            _, obj, prop, computed = node
            if obj == ("id", "datum"):
                if prop[0] != "str":
                    raise ExpressionError("reads a row field by a computed key; name it")
                if not prop[1] or prop[1] in EXPRESSION_FORBIDDEN_NAMES:
                    raise ExpressionError("names a property no expression may read")
                fields.append(prop[1])
            elif computed and _is_index(prop):
                stack.append(obj)
            else:
                raise ExpressionError("reads a property of something other than the row")
        elif kind == "call":
            _, name, args = node
            if name not in profile.expression_functions:
                raise ExpressionError("calls a function outside the expression allowlist")
            arity = _EXACT_ARITY.get(name)
            if arity is not None and len(args) != arity:
                raise ExpressionError(f"calls a function that takes {arity} arguments")
            if name == "pad" and not (
                len(args) >= 2 and _is_index(args[1]) and args[1][1] <= MAX_PAD_LENGTH
            ):
                raise ExpressionError(
                    f"pads to a length that is not a number of at most {MAX_PAD_LENGTH}"
                )
            stack.extend(args)
        elif kind == "array":
            stack.extend(node[1])
        elif kind == "unary":
            stack.append(node[2])
        elif kind == "binary":
            stack.extend((node[2], node[3]))
        else:
            stack.extend(node[1:])
    return fields


def check_expression(text: str, profile: Profile | None = None) -> list[str]:
    """The row fields ``text`` reads (sorted, each once), or
    :class:`ExpressionError` naming why it is outside the profile."""
    if not isinstance(text, str):
        raise ExpressionError("must be an expression string")
    # Measured in UTF-16 code units, as the renderer measures it.
    if len(text.encode("utf-16-le")) // 2 > MAX_EXPRESSION_CHARS:
        raise ExpressionError(f"is longer than {MAX_EXPRESSION_CHARS} characters")
    tokens = _tokenize(text)
    if len(tokens) == 1:
        raise ExpressionError("is empty")
    tree = _ExpressionParser(tokens).parse()
    return sorted(set(_check_expression_tree(tree, profile or PROFILE)))


class Expression(Rule):
    """A Vega expression string inside the profile's grammar and allowlist.
    The row fields it reads are recorded for binding, like any other field."""

    def check(self, value: object, path: str, walk: _Walk) -> object:
        if not isinstance(value, str):
            raise ChartSpecError(f"{_label(path)} must be an expression string", path)
        try:
            fields = check_expression(value, walk.profile)
        except ExpressionError as exc:
            raise ChartSpecError(f"{_label(path)} {exc}", path) from None
        walk.fields.extend((path, escape_field(name)) for name in fields)
        return value

    def describe(self) -> str:
        return "expression"


EXPRESSION = Expression()


# Predicates: structured objects, or an expression string --------------------


def _predicate() -> Rule:
    pred = Lazy(_predicate, "predicate")
    time = {"timeUnit": _time_unit()}
    field_pred = {
        "field": Field(),
        **time,
    }
    return OneOf(
        Obj({**field_pred, "equal": SCALAR}, required=("field", "equal"), what="{field, equal}"),
        Obj({**field_pred, "lt": Num()}, required=("field", "lt"), what="{field, lt}"),
        Obj({**field_pred, "lte": Num()}, required=("field", "lte"), what="{field, lte}"),
        Obj({**field_pred, "gt": Num()}, required=("field", "gt"), what="{field, gt}"),
        Obj({**field_pred, "gte": Num()}, required=("field", "gte"), what="{field, gte}"),
        Obj(
            {**field_pred, "range": Arr(OneOf(Num(), Null()), min_items=2, max_items=2)},
            required=("field", "range"),
            what="{field, range}",
        ),
        Obj(
            {**field_pred, "oneOf": Arr(SCALAR, max_items=MAX_LIST * 4)},
            required=("field", "oneOf"),
            what="{field, oneOf}",
        ),
        Obj({**field_pred, "valid": Bool()}, required=("field", "valid"), what="{field, valid}"),
        Obj({"param": ParamRef(), "empty": Bool()}, required=("param",), what="{param}"),
        Obj({"and": Arr(pred, min_items=1, max_items=16)}, required=("and",), what="{and}"),
        Obj({"or": Arr(pred, min_items=1, max_items=16)}, required=("or",), what="{or}"),
        Obj({"not": pred}, required=("not",), what="{not}"),
        EXPRESSION,
    )


PREDICATE = Lazy(_predicate, "predicate")


# Channels --------------------------------------------------------------------


#: What a channel's constant ``value`` may be. A color slot takes only the
#: color grammar: a free string there would be an SVG paint-server URL.
NUMBER_VALUE = OneOf(Num(), Null())
POSITION_VALUE = OneOf(Num(), Enum({"width", "height"}), Null())
COLOR_VALUE = OneOf(Color(), Null())
TEXT_VALUE = OneOf(Str(MAX_TEXT_CHARS), Num(), Bool(), Null())


def _channel(
    extra: Mapping[str, Rule], *, conditional: bool = True, value: Rule = NUMBER_VALUE
) -> Rule:
    """A channel definition: a field, a datum or a constant value, with the
    keys this channel kind admits."""
    base: dict[str, Rule] = {
        "field": Field(),
        "type": Enum(FIELD_TYPES),
        "aggregate": _aggregate_op(),
        "bin": _bin_params(),
        "timeUnit": _time_unit(),
        "title": OneOf(TITLE_TEXT, Null()),
        "datum": OneOf(SCALAR, Obj({"param": ParamRef()}, required=("param",))),
        "value": value,
    }
    base.update(extra)
    if conditional:
        cond_fields = dict(base)
        cond_fields.pop("title", None)
        cond_fields["param"] = ParamRef()
        cond_fields["test"] = PREDICATE
        cond_fields["empty"] = Bool()
        one = Obj(cond_fields, what="condition")
        base["condition"] = OneOf(one, Arr(one, min_items=1, max_items=8))
    rule = Obj(base, what="channel definition")

    def check(value: object, path: str, walk: _Walk) -> object:
        return _check_channel(rule, value, path, walk)

    return Custom(check, "channel definition", {"object"})


def _check_channel(rule: Obj, value: object, path: str, walk: _Walk) -> object:
    raw = _mapping(value, path)
    admitted = rule.check(raw, path, walk)
    # Vega-Lite guesses a type when one is missing, and guesses wrong for
    # numbers stored as text. A named field names its type.
    if "field" in raw and "type" not in raw:
        raise ChartSpecError(
            f"{_label(path)} must name a type ({', '.join(FIELD_TYPES)}) for its field",
            _join(path, "type"),
        )
    return admitted


POSITION = {
    "scale": OneOf(_scale(), Null()),
    "axis": _axis(),
    "sort": _sort(),
    "stack": OneOf(Null(), Bool(), Enum({"zero", "normalize", "center"})),
    "format": Format(),
    "formatType": Enum({"number", "time", "utc"}),
    "bandPosition": Num(0, 1),
}
SECONDARY = {"format": Format(), "formatType": Enum({"number", "time", "utc"})}
OFFSET = {"scale": OneOf(_scale(), Null()), "sort": _sort()}
POLAR = {
    "scale": OneOf(_scale(), Null()),
    "sort": _sort(),
    "stack": OneOf(Null(), Bool(), Enum({"zero", "normalize", "center"})),
}
MARK_PROPERTY = {
    "scale": OneOf(_scale(), Null()),
    "legend": _legend(),
    "sort": _sort(),
    "format": Format(),
    "formatType": Enum({"number", "time", "utc"}),
}
#: Paint and shape channels always go through a scale: ``scale: null`` would
#: draw the data's own strings as fills (a paint-server URL) or symbol paths.
SCALED_MARK_PROPERTY = {**MARK_PROPERTY, "scale": _scale()}
TEXT = {"format": Format(), "formatType": Enum({"number", "time", "utc"})}
FACET = {
    "header": _header(),
    "sort": _sort(),
    "spacing": PIXELS,
    "align": Enum({"all", "each", "none"}),
    "center": Bool(),
}
ORDER = {"sort": OneOf(SORT_ORDER, Null())}


def _list_or_one(rule: Rule) -> Rule:
    return OneOf(rule, Arr(rule, min_items=0, max_items=32))


# Marks -----------------------------------------------------------------------

COMMON_MARK_PROPS: dict[str, Rule] = {
    "tooltip": OneOf(
        Bool(), Null(), Obj({"content": Enum({"data", "encoding"})}, what="tooltip content")
    ),
    "opacity": OPACITY,
    "fillOpacity": OPACITY,
    "strokeOpacity": OPACITY,
    "color": Color(),
    "fill": Color(),
    "stroke": Color(),
    "strokeWidth": Num(0, 50),
    "strokeDash": STROKE_DASH,
    "filled": Bool(),
    "clip": Bool(),
    "orient": Enum({"horizontal", "vertical"}),
    "size": Num(0, 100_000),
    "aria": Bool(),
    "description": Str(MAX_TEXT_CHARS),
    "invalid": OneOf(
        Null(),
        Enum(
            {
                "filter",
                "break-paths-filter-domains",
                "break-paths-show-domains",
                "show",
                "break-paths-show-path-domains",
            }
        ),
    ),
}
INTERPOLATE = Enum(
    {
        "linear",
        "linear-closed",
        "step",
        "step-before",
        "step-after",
        "basis",
        "cardinal",
        "catmull-rom",
        "monotone",
        "natural",
        "bundle",
    }
)
POINT_OVERLAY = OneOf(
    Bool(),
    Const("transparent"),
    Obj(
        {
            "filled": Bool(),
            "size": Num(0, 100_000),
            "opacity": OPACITY,
            "color": Color(),
            "fill": Color(),
        },
        what="point overlay",
    ),
)
LINE_OVERLAY = OneOf(
    Bool(),
    Obj({"strokeWidth": Num(0, 50), "opacity": OPACITY, "color": Color()}, what="line overlay"),
)
CORNER = {
    "cornerRadius": Num(0, 100),
    "cornerRadiusEnd": Num(0, 100),
    "cornerRadiusTopLeft": Num(0, 100),
    "cornerRadiusTopRight": Num(0, 100),
    "cornerRadiusBottomLeft": Num(0, 100),
    "cornerRadiusBottomRight": Num(0, 100),
}
SHAPE = Enum(
    {
        "circle",
        "square",
        "cross",
        "diamond",
        "triangle-up",
        "triangle-down",
        "triangle-right",
        "triangle-left",
        "triangle",
        "arrow",
        "wedge",
        "stroke",
    }
)
COMPOSITE_PART = OneOf(
    Bool(),
    Obj(
        {"color": Color(), "opacity": OPACITY, "strokeWidth": Num(0, 50), "size": Num(0, 1000)},
        what="part style",
    ),
)


def _register_marks(p: Profile) -> None:
    p.register_mark(
        "line", {"interpolate": INTERPOLATE, "point": POINT_OVERLAY, "tension": Num(0, 1)}
    )
    p.register_mark(
        "area",
        {
            "interpolate": INTERPOLATE,
            "point": POINT_OVERLAY,
            "line": LINE_OVERLAY,
            "tension": Num(0, 1),
        },
    )
    p.register_mark(
        "bar",
        {
            **CORNER,
            "binSpacing": Num(0, 100),
            "width": OneOf(PIXELS, Obj({"band": Num(0, 1)}, required=("band",))),
            "height": OneOf(PIXELS, Obj({"band": Num(0, 1)}, required=("band",))),
        },
    )
    p.register_mark("point", {"shape": SHAPE})
    p.register_mark("circle", {})
    p.register_mark("square", {})
    p.register_mark("tick", {"thickness": Num(0, 100), "bandSize": PIXELS})
    p.register_mark("rect", {**CORNER, "binSpacing": Num(0, 100)})
    p.register_mark("rule", {})
    p.register_mark(
        "text",
        {
            "text": Str(MAX_TEXT_CHARS),
            "align": Enum({"left", "center", "right"}),
            "baseline": Enum({"top", "middle", "bottom", "alphabetic", "line-top", "line-bottom"}),
            "dx": Num(-MAX_DIMENSION, MAX_DIMENSION),
            "dy": Num(-MAX_DIMENSION, MAX_DIMENSION),
            "angle": ANGLE,
            "fontSize": Num(1, 200),
            "fontWeight": FONT_WEIGHT,
            "limit": PIXELS,
        },
    )
    p.register_mark(
        "arc",
        {
            "innerRadius": PIXELS,
            "outerRadius": PIXELS,
            "padAngle": Num(0, 6.3),
            "cornerRadius": Num(0, 100),
            "radiusOffset": Num(-MAX_DIMENSION, MAX_DIMENSION),
            "thetaOffset": Num(-6.3, 6.3),
        },
    )
    p.register_mark(
        "boxplot",
        {
            "extent": OneOf(Const("min-max"), Num(0, 100)),
            "median": COMPOSITE_PART,
            "box": COMPOSITE_PART,
            "rule": COMPOSITE_PART,
            "outliers": COMPOSITE_PART,
            "ticks": COMPOSITE_PART,
        },
    )
    p.register_mark(
        "errorbar",
        {
            "extent": Enum({"ci", "stderr", "stdev", "iqr"}),
            "ticks": COMPOSITE_PART,
            "rule": COMPOSITE_PART,
            "thickness": Num(0, 100),
        },
    )
    p.register_mark(
        "errorband",
        {
            "extent": Enum({"ci", "stderr", "stdev", "iqr"}),
            "band": COMPOSITE_PART,
            "borders": COMPOSITE_PART,
            "interpolate": INTERPOLATE,
        },
    )


def _check_mark(value: object, path: str, walk: _Walk) -> object:
    marks = walk.profile.marks
    if isinstance(value, str):
        if value not in marks:
            raise ChartSpecError(f"{_label(path)} must be one of {sorted(marks)}", path)
        walk.marks.add(value)
        return value
    raw = _mapping(value, path)
    kind = raw.get("type")
    if not isinstance(kind, str) or kind not in marks:
        raise ChartSpecError(
            f"{_join(path, 'type')} must be one of {sorted(marks)}", _join(path, "type")
        )
    walk.marks.add(kind)
    rule = Obj({"type": Const(kind), **COMMON_MARK_PROPS, **marks[kind]}, what=f"{kind} mark")
    return rule.check(raw, path, walk)


MARK = Custom(_check_mark, "mark", {"string", "object"})


def _register_channels(p: Profile) -> None:
    for name in ("x", "y"):
        p.register_channel(name, _channel(POSITION, value=POSITION_VALUE))
    for name in ("x2", "y2", "xError", "yError", "xError2", "yError2"):
        p.register_channel(name, _channel(SECONDARY, conditional=False))
    for name in ("xOffset", "yOffset"):
        p.register_channel(name, _channel(OFFSET, conditional=False))
    for name in ("theta", "radius"):
        p.register_channel(name, _channel(POLAR, conditional=False))
    for name in ("theta2", "radius2"):
        p.register_channel(name, _channel(SECONDARY, conditional=False))
    for name in ("color", "fill", "stroke"):
        p.register_channel(name, _channel(SCALED_MARK_PROPERTY, value=COLOR_VALUE))
    for name in ("opacity", "fillOpacity", "strokeOpacity", "size", "strokeWidth", "angle"):
        p.register_channel(name, _channel(MARK_PROPERTY))
    p.register_channel("shape", _channel(SCALED_MARK_PROPERTY, value=OneOf(SHAPE, Null())))
    p.register_channel("strokeDash", _channel(MARK_PROPERTY, value=OneOf(STROKE_DASH, Null())))
    p.register_channel("text", _channel(TEXT, value=TEXT_VALUE))
    p.register_channel(
        "tooltip",
        OneOf(
            Null(),
            _channel(TEXT, value=TEXT_VALUE),
            Arr(_channel(TEXT, conditional=False, value=TEXT_VALUE), max_items=32),
        ),
    )
    p.register_channel("detail", _list_or_one(_channel({}, conditional=False)))
    p.register_channel(
        "order",
        OneOf(
            _channel(ORDER, conditional=False), Arr(_channel(ORDER, conditional=False), max_items=8)
        ),
    )
    for name in ("row", "column", "facet"):
        p.register_channel(name, _channel(FACET, conditional=False))


def _check_encoding(value: object, path: str, walk: _Walk) -> object:
    raw = _mapping(value, path)
    channels = walk.profile.channels
    unknown = sorted(set(raw) - set(channels))
    if unknown:
        raise ChartSpecError(f"{_label(path)} carries unsupported channels: {unknown}", path)
    return {name: channels[name].check(item, _join(path, name), walk) for name, item in raw.items()}


ENCODING = Custom(_check_encoding, "encoding", {"object"})


# Transforms ------------------------------------------------------------------


def _as_list(value: object) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        return [item for item in value if isinstance(item, str)]
    return []


def _outputs_of(entries_key: str) -> Callable[[Mapping[str, Any]], Iterable[str]]:
    def outputs(t: Mapping[str, Any]) -> Iterable[str]:
        return [
            e["as"]
            for e in t.get(entries_key, [])
            if isinstance(e, Mapping) and isinstance(e.get("as"), str)
        ]

    return outputs


def _register_transforms(p: Profile) -> None:
    agg_entry = Obj(
        {"op": Registry(lambda q: q.aggregates, "aggregate op"), "field": Field(), "as": Output()},
        required=("op", "as"),
        what="aggregate entry",
    )
    groupby = Arr(Field(), max_items=16)
    sort_entry = Obj(
        {"field": Field(), "order": SORT_ORDER}, required=("field",), what="sort entry"
    )
    window_ops = {
        "row_number",
        "rank",
        "dense_rank",
        "percent_rank",
        "cume_dist",
        "ntile",
        "lag",
        "lead",
        "first_value",
        "last_value",
        "nth_value",
    }
    p.register_transform(
        Transform(
            "filter",
            Obj({"filter": PREDICATE}, required=("filter",)),
            lambda t: [],
            "keep rows matching a predicate object or a bounded expression",
        )
    )
    p.register_transform(
        Transform(
            "calculate",
            Obj({"calculate": EXPRESSION, "as": Output()}, required=("calculate", "as")),
            lambda t: _as_list(t.get("as")),
            "derive a field from a bounded expression over the row",
        )
    )
    p.register_transform(
        Transform(
            "aggregate",
            Obj(
                {"aggregate": Arr(agg_entry, min_items=1, max_items=16), "groupby": groupby},
                required=("aggregate",),
            ),
            _outputs_of("aggregate"),
            "group and summarize",
        )
    )
    p.register_transform(
        Transform(
            "joinaggregate",
            Obj(
                {"joinaggregate": Arr(agg_entry, min_items=1, max_items=16), "groupby": groupby},
                required=("joinaggregate",),
            ),
            _outputs_of("joinaggregate"),
            "summarize and keep every row",
        )
    )
    p.register_transform(
        Transform(
            "window",
            Obj(
                {
                    "window": Arr(
                        Obj(
                            {
                                "op": OneOf(
                                    Enum(window_ops),
                                    Registry(lambda q: q.aggregates, "aggregate op"),
                                ),
                                "field": Field(),
                                "param": Num(0, 1_000_000, integer=True),
                                "as": Output(),
                            },
                            required=("op", "as"),
                            what="window entry",
                        ),
                        min_items=1,
                        max_items=16,
                    ),
                    "frame": Arr(
                        OneOf(Num(-1_000_000, 1_000_000, integer=True), Null()),
                        min_items=2,
                        max_items=2,
                    ),
                    "groupby": groupby,
                    "sort": Arr(sort_entry, max_items=8),
                    "ignorePeers": Bool(),
                },
                required=("window",),
            ),
            _outputs_of("window"),
            "running and ranked values (rank, lag, cumulative sums)",
        )
    )
    p.register_transform(
        Transform(
            "bin",
            Obj(
                {
                    "bin": _bin_params(),
                    "field": Field(),
                    "as": OneOf(Output(), Arr(Output(), min_items=2, max_items=2)),
                },
                required=("bin", "field", "as"),
            ),
            lambda t: _as_list(t.get("as")) + [f"{a}_end" for a in _as_list(t.get("as"))[:1]],
            "bucket a numeric field",
        )
    )
    p.register_transform(
        Transform(
            "timeUnit",
            Obj(
                {"timeUnit": _time_unit(), "field": Field(), "as": Output()},
                required=("timeUnit", "field", "as"),
            ),
            lambda t: _as_list(t.get("as")) + [f"{a}_end" for a in _as_list(t.get("as"))],
            "truncate a date to a unit",
        )
    )
    p.register_transform(
        Transform(
            "fold",
            Obj(
                {
                    "fold": Arr(Field(), min_items=1, max_items=MAX_ROW_FIELDS),
                    "as": Arr(Output(), min_items=2, max_items=2),
                },
                required=("fold",),
            ),
            lambda t: _as_list(t.get("as")) or ["key", "value"],
            "wide to long",
        )
    )
    p.register_transform(
        Transform(
            "pivot",
            Obj(
                {
                    "pivot": Field(),
                    "value": Field(),
                    "groupby": groupby,
                    "limit": Num(0, MAX_ROW_FIELDS, integer=True),
                    "op": Registry(lambda q: q.aggregates, "aggregate op"),
                },
                required=("pivot", "value"),
            ),
            lambda t: None,
            "long to wide (its output fields are the data's values)",
        )
    )
    fit = {
        "groupby": groupby,
        "extent": Arr(Num(), min_items=2, max_items=2),
        "as": Arr(Output(), min_items=2, max_items=2),
    }
    p.register_transform(
        Transform(
            "regression",
            Obj(
                {
                    "regression": Field(),
                    "on": Field(),
                    "method": Enum({"linear", "log", "exp", "pow", "quad", "poly"}),
                    "order": Num(1, 10, integer=True),
                    **fit,
                },
                required=("regression", "on"),
            ),
            lambda t: _as_list(t.get("as")) or [t.get("on", ""), t.get("regression", "")],
            "least-squares fit line",
        )
    )
    p.register_transform(
        Transform(
            "loess",
            Obj(
                {"loess": Field(), "on": Field(), "bandwidth": Num(0, 1), **fit},
                required=("loess", "on"),
            ),
            lambda t: _as_list(t.get("as")) or [t.get("on", ""), t.get("loess", "")],
            "locally weighted smoothing",
        )
    )
    p.register_transform(
        Transform(
            "density",
            Obj(
                {
                    "density": Field(),
                    "groupby": groupby,
                    "cumulative": Bool(),
                    "counts": Bool(),
                    "bandwidth": Num(0, 1e15),
                    "extent": Arr(Num(), min_items=2, max_items=2),
                    "minsteps": Num(1, 10_000, integer=True),
                    "maxsteps": Num(1, 10_000, integer=True),
                    "steps": Num(1, 10_000, integer=True),
                    "as": Arr(Output(), min_items=2, max_items=2),
                },
                required=("density",),
            ),
            lambda t: _as_list(t.get("as")) or ["value", "density"],
            "kernel density estimate",
        )
    )
    p.register_transform(
        Transform(
            "quantile",
            Obj(
                {
                    "quantile": Field(),
                    "groupby": groupby,
                    "probs": Arr(Num(0, 1), max_items=1000),
                    "step": Num(1e-6, 1),
                    "as": Arr(Output(), min_items=2, max_items=2),
                },
                required=("quantile",),
            ),
            lambda t: _as_list(t.get("as")) or ["prob", "value"],
            "quantiles (Q-Q plots)",
        )
    )
    p.register_transform(
        Transform(
            "impute",
            Obj(
                {
                    "impute": Field(),
                    "key": Field(),
                    "keyvals": Arr(SCALAR, max_items=MAX_LIST * 4),
                    "method": Enum({"value", "mean", "median", "max", "min"}),
                    "value": SCALAR,
                    "groupby": groupby,
                    "frame": Arr(
                        OneOf(Num(-1_000_000, 1_000_000, integer=True), Null()),
                        min_items=2,
                        max_items=2,
                    ),
                },
                required=("impute", "key"),
            ),
            lambda t: [],
            "fill gaps in a series",
        )
    )
    p.register_transform(
        Transform(
            "stack",
            Obj(
                {
                    "stack": Field(),
                    "groupby": groupby,
                    "offset": Enum({"zero", "center", "normalize"}),
                    "sort": Arr(sort_entry, max_items=8),
                    "as": Arr(Output(), min_items=2, max_items=2),
                },
                required=("stack", "groupby", "as"),
            ),
            lambda t: _as_list(t.get("as")),
            "stack values",
        )
    )


def _check_transform(value: object, path: str, walk: _Walk) -> object:
    raw = _mapping(value, path)
    transforms = walk.profile.transforms
    keys = [key for key in raw if key in transforms]
    if len(keys) != 1:
        raise ChartSpecError(
            f"{_label(path)} must be exactly one of the transforms {sorted(transforms)}", path
        )
    registered = transforms[keys[0]]
    admitted = registered.rule.check(raw, path, walk)
    outputs = registered.outputs(raw)
    if outputs is None:
        walk.opaque_outputs = True
    else:
        walk.produced.update(name for name in outputs if isinstance(name, str) and name)
    return admitted


TRANSFORMS = Arr(Custom(_check_transform, "transform", {"object"}), max_items=MAX_TRANSFORMS)


# Selections ------------------------------------------------------------------


def _check_param(value: object, path: str, walk: _Walk) -> object:
    raw = _mapping(value, path)
    name = raw.get("name")
    if not isinstance(name, str) or not re.match(PARAM_NAME, name):
        raise ChartSpecError(
            f"{_join(path, 'name')} must be a name of letters, digits and _", _join(path, "name")
        )
    if name in RESERVED_PARAM_NAMES:
        raise ChartSpecError(
            f"{_join(path, 'name')} is reserved by the renderer", _join(path, "name")
        )
    if name in walk.params:
        raise ChartSpecError(f"{_join(path, 'name')} repeats a selection name", _join(path, "name"))
    select = Obj(
        {
            "type": Enum({"interval", "point"}),
            "encodings": Arr(Registry(lambda p: p.channels, "channel"), max_items=4),
            "fields": Arr(Field(), max_items=8),
            "nearest": Bool(),
            "toggle": Bool(),
            "clear": Bool(),
            "resolve": Enum({"global", "union", "intersect"}),
            "mark": Obj(
                {
                    "fill": Color(),
                    "fillOpacity": OPACITY,
                    "stroke": Color(),
                    "strokeOpacity": OPACITY,
                    "strokeWidth": Num(0, 50),
                    "strokeDash": STROKE_DASH,
                },
                what="brush style",
            ),
        },
        required=("type",),
        what="selection",
    )
    rule = Obj(
        {
            "name": Str(64),
            "select": OneOf(Enum({"interval", "point"}), select),
            # Only the two bindings that are interactions inside the chart:
            # zoom and pan ("scales") and a clickable legend. An input-element
            # binding is a widget, a later seam.
            "bind": Enum({"scales", "legend"}),
            "views": Arr(Str(64, PARAM_NAME), max_items=MAX_VIEWS),
        },
        required=("name", "select"),
        what="selection parameter",
    )
    admitted = rule.check(raw, path, walk)
    walk.params[name] = path
    return admitted


PARAMS = Arr(Custom(_check_param, "selection parameter", {"object"}), max_items=MAX_PARAMS)


# Data ------------------------------------------------------------------------


def _check_rows(value: object, path: str, walk: _Walk) -> object:
    if not isinstance(value, list):
        raise ChartSpecError(f"{_label(path)} must be a list of row objects", path)
    walk.rows += len(value)
    if walk.rows > MAX_INLINE_ROWS:
        raise ChartSpecError(
            f"{_label(path)} brings the chart past {MAX_INLINE_ROWS} inline rows; "
            "aggregate first, or sample (alkera.chart samples for you)",
            path,
        )
    for i, row in enumerate(value):
        row_path = _index(path, i)
        if not isinstance(row, Mapping):
            raise ChartSpecError(f"{_label(row_path)} must be an object of field values", row_path)
        if len(row) > MAX_ROW_FIELDS:
            raise ChartSpecError(
                f"{_label(row_path)} has more than {MAX_ROW_FIELDS} fields", row_path
            )
        for key, cell in row.items():
            if not isinstance(key, str) or len(key) > MAX_FIELD_CHARS:
                raise ChartSpecError(
                    f"{_label(row_path)} has a field name that is not a string of at most "
                    f"{MAX_FIELD_CHARS} characters",
                    row_path,
                )
            walk.columns.add(key)
            if cell is None or isinstance(cell, bool):
                continue
            if isinstance(cell, (int, float)):
                if isinstance(cell, float) and not math.isfinite(cell):
                    raise ChartSpecError(
                        f"{_label(row_path)} holds a number that is not finite (use null)", row_path
                    )
                continue
            if isinstance(cell, str):
                if len(cell) > MAX_CELL_CHARS:
                    raise ChartSpecError(
                        f"{_label(row_path)} holds a value longer than {MAX_CELL_CHARS} characters",
                        row_path,
                    )
                continue
            raise ChartSpecError(
                f"{_label(row_path)} holds a value that is not a string, number, boolean or null",
                row_path,
            )
    return [dict(row) for row in value]


ROWS = Custom(_check_rows, "row list", {"array"})


#: Delimited-text formats. Vega parses them by compiling a row function with
#: ``new Function``, which the renderer's content security policy blocks.
_DELIMITED_FORMATS = frozenset({"csv", "tsv", "dsv"})
_DELIMITED_SUFFIXES = (".csv", ".tsv")


def _refuse_delimited(raw: Mapping[str, Any], path: str) -> None:
    fmt = raw.get("format")
    url = raw.get("url")
    delimited = (
        (isinstance(fmt, Mapping) and str(fmt.get("type", "")).lower() in _DELIMITED_FORMATS)
        or isinstance(raw.get("values"), str)
        or (
            isinstance(url, str)
            and url.split("?", 1)[0].split("#", 1)[0].lower().endswith(_DELIMITED_SUFFIXES)
        )
    )
    if delimited:
        raise ChartSpecError(
            f"{_label(path)} holds CSV or TSV text, which charts do not parse; give the "
            "rows inline as a list of objects (alkera.chart reads CSV for you)",
            path,
        )


def _check_data(value: object, path: str, walk: _Walk) -> object:
    policy = walk.policy
    raw = _mapping(value, path)
    if not policy.inline:
        raise ChartSpecError(
            f"{_label(path)} is not admitted: this chart's rows come from its result", path
        )
    _refuse_delimited(raw, path)
    if "values" in raw:
        return Obj(
            {"values": ROWS, "name": Str(64)}, required=("values",), what="inline data"
        ).check(raw, path, walk)
    rule = Obj({"name": Str(128, r"^[A-Za-z0-9_.:-]+$")}, required=("name",), what="named data")
    admitted = rule.check(raw, path, walk)
    walk.data_refs.append((_join(path, "name"), raw["name"]))
    return admitted


DATA = Custom(_check_data, "data", {"object"})


def _check_datasets(value: object, path: str, walk: _Walk) -> object:
    raw = _mapping(value, path)
    if not walk.policy.inline:
        raise ChartSpecError(
            f"{_label(path)} is not admitted: this chart's rows come from its result", path
        )
    if len(raw) > MAX_DATASETS:
        raise ChartSpecError(f"{_label(path)} holds more than {MAX_DATASETS} datasets", path)
    out: dict[str, object] = {}
    for name, rows in raw.items():
        Str(128, r"^[A-Za-z0-9_.:-]+$").check(name, path, walk)
        walk.dataset_names.add(name)
        if isinstance(rows, str):
            _refuse_delimited({"values": rows}, _join(path, name))
        out[name] = ROWS.check(rows, _join(path, name), walk)
    return out


# Views -----------------------------------------------------------------------

TITLE = OneOf(
    Str(MAX_TEXT_CHARS),
    Obj(
        {
            "text": TITLE_TEXT,
            "subtitle": TITLE_TEXT,
            "anchor": Enum({"start", "middle", "end"}),
            "orient": Enum({"top", "bottom", "left", "right"}),
        },
        required=("text",),
        what="title",
    ),
)
SIZE = OneOf(
    Num(1, MAX_DIMENSION, integer=True),
    Const("container"),
    Obj({"step": Num(1, MAX_DIMENSION)}, required=("step",), what="{step}"),
)
RESOLVE_MODE = Enum({"shared", "independent"})
RESOLVE = Obj(
    {
        kind: Obj(
            {
                ch: RESOLVE_MODE
                for ch in (
                    "x",
                    "y",
                    "color",
                    "opacity",
                    "size",
                    "shape",
                    "theta",
                    "radius",
                    "xOffset",
                    "yOffset",
                    "fill",
                    "stroke",
                )
            }
        )
        for kind in ("scale", "axis", "legend")
    },
    what="resolve",
)
VIEW_COMMON: dict[str, Rule] = {
    "title": TITLE,
    "description": Str(MAX_DESCRIPTION_CHARS),
    "name": Str(64, PARAM_NAME),
    "data": DATA,
    "transform": TRANSFORMS,
    "width": SIZE,
    "height": SIZE,
}
COMPOSITIONS = ("layer", "hconcat", "vconcat", "concat", "facet")


def _check_view(value: object, path: str, walk: _Walk, *, in_layer: bool = False) -> object:
    raw = _mapping(value, path)
    walk.views += 1
    if walk.views > MAX_VIEWS:
        raise ChartSpecError(f"{_label(path)} brings the chart past {MAX_VIEWS} views", path)
    kinds = [key for key in ("mark", *COMPOSITIONS) if key in raw]
    if len(kinds) != 1:
        raise ChartSpecError(
            f"{_label(path)} must have exactly one of mark, layer, hconcat, vconcat, "
            "concat or facet",
            path,
        )
    kind = kinds[0]
    if in_layer and kind not in ("mark", "layer"):
        raise ChartSpecError(f"{_label(path)} must be a mark or a layer view", path)
    walk.depth += 1
    if walk.depth > MAX_NESTING:
        raise ChartSpecError(f"{_label(path)} nests compositions deeper than {MAX_NESTING}", path)
    try:
        fields = dict(VIEW_COMMON)
        child = Custom(lambda v, p, w: _check_view(v, p, w), "view", {"object"})
        if kind == "mark":
            fields.update({"mark": MARK, "encoding": ENCODING, "params": PARAMS})
        elif kind == "layer":
            layer_child = Custom(
                lambda v, p, w: _check_view(v, p, w, in_layer=True), "layer view", {"object"}
            )
            fields.update(
                {
                    "layer": Arr(layer_child, min_items=1, max_items=MAX_LAYERS),
                    "encoding": ENCODING,
                    "resolve": RESOLVE,
                }
            )
        elif kind == "facet":
            facet_child = Custom(
                lambda v, p, w: _check_view(v, p, w, in_layer=True), "faceted view", {"object"}
            )
            fields.update(
                {
                    "facet": OneOf(
                        Obj(
                            {
                                "row": _channel(FACET, conditional=False),
                                "column": _channel(FACET, conditional=False),
                            },
                            what="row/column facet",
                        ),
                        _channel(FACET, conditional=False),
                    ),
                    "spec": facet_child,
                    "columns": Num(1, 64, integer=True),
                    "resolve": RESOLVE,
                    "spacing": PIXELS,
                }
            )
            if "spec" not in raw:
                raise ChartSpecError(
                    f"{_label(path)} must name spec for its facet", _join(path, "spec")
                )
        else:
            fields.update(
                {
                    kind: Arr(child, min_items=1, max_items=MAX_VIEWS),
                    "resolve": RESOLVE,
                    "spacing": PIXELS,
                }
            )
            if kind == "concat":
                fields["columns"] = Num(1, 64, integer=True)
        if path == "":
            fields.update(TOP_LEVEL)
        if not walk.policy.inline:
            # A bound chart's rows are its result's; a data block is simply
            # not part of its vocabulary.
            fields.pop("data", None)
            fields.pop("datasets", None)
        return Obj(fields, what="view").check(raw, path, walk)
    finally:
        walk.depth -= 1


def _check_usermeta(value: object, path: str, walk: _Walk) -> object:
    return Obj(
        {
            "alkera": Obj(
                {
                    "sampled": Obj(
                        {
                            "rows": Num(0, MAX_INLINE_ROWS, integer=True),
                            "of": Num(0, 1e15, integer=True),
                            "method": Enum({"systematic", "head"}),
                        },
                        required=("rows", "of", "method"),
                        what="sampling note",
                    ),
                    "profile": Str(16, r"^\d+\.\d+\.\d+$"),
                },
                what="alkera metadata",
            )
        },
        what="usermeta",
    ).check(value, path, walk)


TOP_LEVEL: dict[str, Rule] = {
    "$schema": Str(80, SCHEMA_PATTERN.pattern, "Vega-Lite v5 or v6 schema URL"),
    # Selections over a composition name the views they live in.
    "params": PARAMS,
    "datasets": Custom(_check_datasets, "datasets", {"object"}),
    "usermeta": Custom(_check_usermeta, "usermeta", {"object"}),
    # Altair writes its default view size here; the theme is otherwise ours.
    "config": Obj(
        {
            "view": Obj(
                {
                    "continuousWidth": Num(1, MAX_DIMENSION),
                    "continuousHeight": Num(1, MAX_DIMENSION),
                    "discreteWidth": OneOf(
                        Num(1, MAX_DIMENSION),
                        Obj({"step": Num(1, MAX_DIMENSION)}, required=("step",)),
                    ),
                    "discreteHeight": OneOf(
                        Num(1, MAX_DIMENSION),
                        Obj({"step": Num(1, MAX_DIMENSION)}, required=("step",)),
                    ),
                    "stroke": OneOf(Color(), Null()),
                    "strokeWidth": Num(0, 50),
                },
                what="view config",
            )
        },
        what="config",
    ),
    "autosize": OneOf(
        Enum({"pad", "fit", "fit-x", "fit-y", "none"}),
        Obj(
            {
                "type": Enum({"pad", "fit", "fit-x", "fit-y", "none"}),
                "contains": Enum({"content", "padding"}),
                "resize": Bool(),
            },
            what="autosize",
        ),
    ),
    "padding": OneOf(
        Num(0, 200),
        Obj({side: Num(0, 200) for side in ("top", "bottom", "left", "right")}, what="padding"),
    ),
}


# --------------------------------------------------------------------------
# The default profile and the entry points.
# --------------------------------------------------------------------------


def default_profile() -> Profile:
    p = Profile()
    _register_marks(p)
    _register_channels(p)
    _register_transforms(p)
    p.aggregates.update(
        {
            "count",
            "valid",
            "values",
            "missing",
            "distinct",
            "sum",
            "product",
            "mean",
            "average",
            "variance",
            "variancep",
            "stdev",
            "stdevp",
            "stderr",
            "median",
            "q1",
            "q3",
            "ci0",
            "ci1",
            "min",
            "max",
        }
    )
    units = [
        "year",
        "quarter",
        "month",
        "week",
        "day",
        "dayofyear",
        "date",
        "hours",
        "minutes",
        "seconds",
        "milliseconds",
        "yearquarter",
        "yearquartermonth",
        "yearmonth",
        "yearmonthdate",
        "yearmonthdatehours",
        "yearmonthdatehoursminutes",
        "yearmonthdatehoursminutesseconds",
        "yearweek",
        "yearweekday",
        "yearweekdayhours",
        "yeardayofyear",
        "quartermonth",
        "monthdate",
        "monthdatehours",
        "weekday",
        "hoursminutes",
        "hoursminutesseconds",
        "minutesseconds",
        "secondsmilliseconds",
    ]
    p.time_units.update(units)
    p.expression_functions.update(EXPRESSION_FUNCTIONS)
    p.expression_constants.update(EXPRESSION_CONSTANTS)
    p.time_units.update(f"utc{unit}" for unit in units)
    # Vega's built-in schemes: names resolved inside the bundle, never fetched.
    p.schemes.update(
        {
            "category10",
            "tableau10",
            "tableau20",
            "set2",
            "dark2",
            "paired",
            "blues",
            "greens",
            "greys",
            "oranges",
            "purples",
            "reds",
            "teals",
            "tealblues",
            "viridis",
            "magma",
            "inferno",
            "plasma",
            "cividis",
            "turbo",
            "blueorange",
            "redblue",
            "redgrey",
            "purplegreen",
            "brownbluegreen",
            "spectral",
        }
    )
    p.interactions.update(
        {
            "tooltip": "mark tooltip: true, or a tooltip channel",
            "zoom": 'an interval selection bound to "scales" (wheel to zoom, drag to pan)',
            "brush": "an interval selection, used by a condition or a filter in the same chart",
            "point": "a point selection, optionally bound to the legend",
        }
    )
    return p


#: The profile every Alkera surface validates against.
PROFILE = default_profile()


class ValidatedChart:
    """An admitted spec and what the walk learned about it."""

    __slots__ = (
        "columns",
        "data_refs",
        "fields",
        "marks",
        "opaque_outputs",
        "params",
        "produced",
        "rows",
        "spec",
    )

    def __init__(self, spec: dict[str, Any], walk: _Walk) -> None:
        self.spec = spec
        self.fields: list[tuple[str, str]] = list(walk.fields)
        self.produced: frozenset[str] = frozenset(walk.produced)
        self.opaque_outputs = walk.opaque_outputs
        self.params: frozenset[str] = frozenset(walk.params)
        self.data_refs: list[tuple[str, str]] = list(walk.data_refs)
        self.columns: frozenset[str] = frozenset(walk.columns)
        self.marks: frozenset[str] = frozenset(walk.marks)
        self.rows = walk.rows

    def persisted(self) -> dict[str, Any]:
        """The spec as it is stored: the admitted keys, ``$schema`` named."""
        return dict(self.spec)

    def unbound_fields(self, columns: Iterable[str]) -> list[str]:
        """Paths of the fields this chart reads that neither ``columns`` nor a
        transform provides. Empty when a transform's outputs are data-dependent
        (pivot), since no static reading can name them."""
        if self.opaque_outputs:
            return []
        known = set(columns) | set(self.produced)
        return [path for path, name in self.fields if field_root(name) not in known]


def field_root(name: str) -> str:
    """The top-level column a Vega-Lite field reads: ``a.b`` reads column
    ``a`` (nested access), while ``a\\.b`` is the column literally named
    ``a.b``."""
    out: list[str] = []
    i = 0
    while i < len(name):
        ch = name[i]
        if ch == "\\" and i + 1 < len(name):
            out.append(name[i + 1])
            i += 2
            continue
        if ch in ".[":
            break
        out.append(ch)
        i += 1
    return "".join(out)


def escape_field(column: str) -> str:
    """A column name spelled as a Vega-Lite field that reads exactly it."""
    return re.sub(r"([.\[\]\\])", r"\\\1", column)


def validate(
    spec: object,
    *,
    policy: DataPolicy = INLINE,
    columns: Iterable[str] | None = None,
    profile: Profile | None = None,
) -> ValidatedChart:
    """``spec`` admitted by the profile, or :class:`ChartSpecError`.

    ``columns`` are the fields a host-bound table carries (a result's column
    keys); with them, a field nothing provides is refused. Under an inline
    policy the inline rows' own fields are the columns, so a typo is refused
    without the caller naming anything.
    """
    walk = _Walk(profile or PROFILE, policy)
    raw = _mapping(spec, "")
    admitted = _check_view(raw, "", walk)
    assert isinstance(admitted, dict)
    for path, name in walk.param_refs:
        if name not in walk.params:
            raise ChartSpecError(f"{path} names a selection the chart does not declare", path)
    for path, name in walk.data_refs:
        if name not in walk.dataset_names and not policy.host_tables:
            raise ChartSpecError(f"{path} names a dataset the chart does not carry", path)
    if "$schema" not in admitted:
        admitted = {"$schema": VEGA_LITE_V6_SCHEMA, **admitted}
    chart = ValidatedChart(admitted, walk)
    known: set[str] | None = None
    if columns is not None:
        known = set(columns)
    elif policy.inline and walk.rows and not (policy.host_tables and walk.data_refs):
        known = set(walk.columns)
    if known is not None:
        unbound = chart.unbound_fields(known)
        if unbound:
            raise ChartSpecError(
                f"{unbound[0]} names a field the chart's data does not have", unbound[0]
            )
    return chart


def spec_size(spec: Mapping[str, Any]) -> int:
    """The spec's size as compact JSON, in bytes."""
    return len(json.dumps(spec, separators=(",", ":"), ensure_ascii=False).encode("utf-8"))


__all__ = [
    "BOUND",
    "CHART_MIME",
    "EXPRESSION_CONSTANTS",
    "EXPRESSION_FUNCTIONS",
    "HOSTED",
    "INLINE",
    "MAX_EXPRESSION_CHARS",
    "MAX_EXPRESSION_DEPTH",
    "MAX_INLINE_ROWS",
    "PROFILE",
    "PROFILE_VERSION",
    "VEGA_LITE_V5_SCHEMA",
    "VEGA_LITE_V6_SCHEMA",
    "ChartSpecError",
    "DataPolicy",
    "ExpressionError",
    "Profile",
    "Transform",
    "ValidatedChart",
    "check_expression",
    "default_profile",
    "escape_field",
    "field_root",
    "spec_size",
    "validate",
]
