"""The notebook engine's client API.

``NotebookEngine`` opens notebooks; ``NotebookSession.attach(actor)`` gives a
``NotebookClient`` whose methods read, edit, run, inspect and manage the
kernel, and whose ``events`` stream reports what happens.

The engine classes load on first use. They pull in the session, which imports
the output, plan, event and widget packages, and those import this package's
leaf modules (config, models, errors); loading them eagerly here would make
importing any of those packages first a circular import.
"""

import importlib
from typing import TYPE_CHECKING, Any

from alkera_notebook.document.ops import (
    CellAfterOp,
    CellNotice,
    DeleteCell,
    EditCell,
    GraphCellSummary,
    GraphErrorInfo,
    GraphSummary,
    InsertCell,
    MoveCell,
    NotebookOp,
    NotebookOpError,
    NotebookOpsResult,
    ReplaceCell,
    RestoreCell,
    SetCellConfig,
    SetCellKind,
    SetCellMeta,
    SetCellName,
    SetSetting,
    TextEdit,
)
from alkera_notebook.engine.config import (
    Clock,
    EngineConfig,
    IdSource,
    MemoryPolicy,
    OutputLimits,
    RandomIds,
    SequentialIds,
    SystemClock,
)
from alkera_notebook.engine.errors import (
    EngineClosedError,
    EngineError,
    ForbiddenError,
    KernelUnavailableError,
    NotFoundError,
    QueryRefusedError,
    ReadOnlyError,
)
from alkera_notebook.engine.models import (
    AboveTarget,
    ActingFor,
    Activity,
    ActivityActor,
    ActivityEntry,
    ActivityKind,
    Actor,
    AllTarget,
    BelowTarget,
    CellChange,
    CellsTarget,
    CellState,
    CellStatus,
    EnvAction,
    EnvChange,
    EnvInfo,
    EnvListing,
    EnvPackages,
    EnvResult,
    ErrorInfo,
    GraphCell,
    GraphView,
    InspectQuery,
    InspectResult,
    KernelInfo,
    KernelState,
    NotebookView,
    OutputDetail,
    OutputPart,
    OutputSummary,
    PackageInfo,
    PlanEntry,
    PlanReason,
    Presence,
    QueuedRun,
    ReadQuery,
    RunActor,
    RunAttribution,
    RunInfo,
    RunRecord,
    RunStatus,
    RunTarget,
    RunTrigger,
    Settings,
    SettingsChange,
    StaleTarget,
    SuspendReport,
    VarSummary,
    WidgetAction,
    WidgetAssetRef,
    WidgetInfo,
    WidgetResult,
    system_actor,
)

if TYPE_CHECKING:
    from alkera_notebook.engine.engine import (
        NotebookClient,
        NotebookEngine,
        NotebookSession,
        RunHandle,
    )
    from alkera_notebook.events.models import (
        AnyEvent,
        FrameAttached,
        FrameMessage,
        KernelInterrupt,
        NotebookEvent,
    )

_LAZY: dict[str, str] = {
    "NotebookClient": "alkera_notebook.engine.engine",
    "NotebookEngine": "alkera_notebook.engine.engine",
    "NotebookSession": "alkera_notebook.engine.engine",
    "RunHandle": "alkera_notebook.engine.engine",
    "AnyEvent": "alkera_notebook.events.models",
    "NotebookEvent": "alkera_notebook.events.models",
    "FrameAttached": "alkera_notebook.events.models",
    "FrameMessage": "alkera_notebook.events.models",
    "KernelInterrupt": "alkera_notebook.events.models",
}


def __getattr__(name: str) -> Any:
    module = _LAZY.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    return getattr(importlib.import_module(module), name)


__all__ = [
    "AboveTarget",
    "ActingFor",
    "Activity",
    "ActivityActor",
    "ActivityEntry",
    "ActivityKind",
    "Actor",
    "AllTarget",
    "AnyEvent",
    "BelowTarget",
    "CellAfterOp",
    "CellChange",
    "CellNotice",
    "CellState",
    "CellStatus",
    "CellsTarget",
    "Clock",
    "DeleteCell",
    "EditCell",
    "EngineClosedError",
    "EngineConfig",
    "EngineError",
    "EnvAction",
    "EnvChange",
    "EnvInfo",
    "EnvListing",
    "EnvPackages",
    "EnvResult",
    "ErrorInfo",
    "ForbiddenError",
    "FrameAttached",
    "FrameMessage",
    "GraphCell",
    "GraphCellSummary",
    "GraphErrorInfo",
    "GraphSummary",
    "GraphView",
    "IdSource",
    "InsertCell",
    "InspectQuery",
    "InspectResult",
    "KernelInfo",
    "KernelInterrupt",
    "KernelState",
    "KernelUnavailableError",
    "MemoryPolicy",
    "MoveCell",
    "NotFoundError",
    "NotebookClient",
    "NotebookEngine",
    "NotebookEvent",
    "NotebookOp",
    "NotebookOpError",
    "NotebookOpsResult",
    "NotebookSession",
    "NotebookView",
    "OutputDetail",
    "OutputLimits",
    "OutputPart",
    "OutputSummary",
    "PackageInfo",
    "PlanEntry",
    "PlanReason",
    "Presence",
    "QueryRefusedError",
    "QueuedRun",
    "RandomIds",
    "ReadOnlyError",
    "ReadQuery",
    "ReplaceCell",
    "RestoreCell",
    "RunActor",
    "RunAttribution",
    "RunHandle",
    "RunInfo",
    "RunRecord",
    "RunStatus",
    "RunTarget",
    "RunTrigger",
    "SequentialIds",
    "SetCellConfig",
    "SetCellKind",
    "SetCellMeta",
    "SetCellName",
    "SetSetting",
    "Settings",
    "SettingsChange",
    "StaleTarget",
    "SuspendReport",
    "SystemClock",
    "TextEdit",
    "VarSummary",
    "WidgetAction",
    "WidgetAssetRef",
    "WidgetInfo",
    "WidgetResult",
    "system_actor",
]
