"""The plugin framework — contracts, registry, typed tool, persistence.

This package is the framework ONLY (no concrete integrations). Concrete
plugins live in sibling packages under ``alkera_cli.plugins.<name>/`` and
import from here.
"""

from __future__ import annotations

from alkera_cli.contracts.tool_types import (
    URN,
    AccessEvent,
    ActionDescriptor,
    CapToken,
    ColumnMeta,
    ConnectionOrigin,
    CostEstimate,
    CredentialMode,
    CredentialRef,
    Effect,
    Environment,
    QueryResult,
    RelationMeta,
    SurfaceKind,
    TableMeta,
    Watermark,
    environment_for,
)
from alkera_cli.plugins.plugin_base.capabilities import (
    Capability,
    CapabilitySet,
    CloneCapability,
    DatabaseCapabilityGroup,
    EstimateSQLCostCapability,
    IntegrationSdkCapability,
    IntrospectSchemaCapability,
    QueryHistoryCapability,
    RunSQLCapability,
)
from alkera_cli.plugins.plugin_base.connection import (
    Connection,
    ConnectionBuild,
    ConnectionBuildResult,
    Credential,
    CredentialManager,
    KeyPairCredential,
    OAuthCredential,
    TokenCredential,
    UserPassCredential,
    normalize_connection_build,
)
from alkera_cli.plugins.plugin_base.connection_form import (
    AuthMethodSchema,
    ConnectionFormSchema,
    FormField,
    OAuthSpec,
)
from alkera_cli.plugins.plugin_base.connector import Connector
from alkera_cli.plugins.plugin_base.cost import (
    CostActual,
    CostCheck,
    CostDecision,
    CostDeniedError,
    CostLedger,
    CostLedgerEntry,
    CostLimits,
    CostReservation,
    CostState,
    check_cost,
    gate_cost,
    release_cost,
    settle_cost,
)
from alkera_cli.plugins.plugin_base.credential_manager import (
    CredentialResolutionError,
    LocalCredentialManager,
    named_credential_ref,
    named_credential_refs,
    register_credential_resolver,
)
from alkera_cli.plugins.plugin_base.enablement import PluginEnablementStore
from alkera_cli.plugins.plugin_base.plugin import (
    ActivationSpec,
    ConnectionSignal,
    NodeCapabilities,
    Plugin,
    PluginConnectionInfo,
    PluginInfo,
    PluginManifest,
    Registrar,
    WorkspaceEvent,
)
from alkera_cli.plugins.plugin_base.registry import ConnectionValidationError, PluginRegistry
from alkera_cli.plugins.plugin_base.state import PluginState, PluginStore
from alkera_cli.plugins.plugin_base.surfaces import (
    PROBE_RESULT_ATTRIBUTE,
    AgentDefinition,
    AgentProvider,
    CapabilityProvider,
    ClassifierProvider,
    ClassifyCtx,
    ConnectionProbeResult,
    ConnectionProvider,
    ContextProvider,
    LineageProvider,
    ProbeProvider,
    RefreshProvider,
    RefreshSpec,
    SkillDef,
    SkillProvider,
    ToolProvider,
    WorkspaceContext,
    cached_probe_result,
)
from alkera_cli.plugins.plugin_base.tool import (
    Tool,
    ToolContext,
    ToolError,
    ToolRegistry,
    ToolSpec,
)

__all__ = [
    "PROBE_RESULT_ATTRIBUTE",
    "URN",
    "AccessEvent",
    "ActionDescriptor",
    "ActivationSpec",
    "AgentDefinition",
    "AgentProvider",
    "AuthMethodSchema",
    "CapToken",
    "Capability",
    "CapabilityProvider",
    "CapabilitySet",
    "ClassifierProvider",
    "ClassifyCtx",
    "CloneCapability",
    "ColumnMeta",
    "Connection",
    "ConnectionBuild",
    "ConnectionBuildResult",
    "ConnectionFormSchema",
    "ConnectionOrigin",
    "ConnectionProbeResult",
    "ConnectionProvider",
    "ConnectionSignal",
    "ConnectionValidationError",
    "Connector",
    "ContextProvider",
    "CostActual",
    "CostCheck",
    "CostDecision",
    "CostDeniedError",
    "CostEstimate",
    "CostLedger",
    "CostLedgerEntry",
    "CostLimits",
    "CostReservation",
    "CostState",
    "Credential",
    "CredentialManager",
    "CredentialMode",
    "CredentialRef",
    "CredentialResolutionError",
    "DatabaseCapabilityGroup",
    "Effect",
    "Environment",
    "EstimateSQLCostCapability",
    "FormField",
    "IntegrationSdkCapability",
    "IntrospectSchemaCapability",
    "KeyPairCredential",
    "LineageProvider",
    "LocalCredentialManager",
    "NodeCapabilities",
    "OAuthCredential",
    "OAuthSpec",
    "Plugin",
    "PluginConnectionInfo",
    "PluginEnablementStore",
    "PluginInfo",
    "PluginManifest",
    "PluginRegistry",
    "PluginState",
    "PluginStore",
    "ProbeProvider",
    "QueryHistoryCapability",
    "QueryResult",
    "RefreshProvider",
    "RefreshSpec",
    "Registrar",
    "RelationMeta",
    "RunSQLCapability",
    "SkillDef",
    "SkillProvider",
    "SurfaceKind",
    "TableMeta",
    "TokenCredential",
    "Tool",
    "ToolContext",
    "ToolError",
    "ToolProvider",
    "ToolRegistry",
    "ToolSpec",
    "UserPassCredential",
    "Watermark",
    "WorkspaceContext",
    "WorkspaceEvent",
    "cached_probe_result",
    "check_cost",
    "environment_for",
    "gate_cost",
    "named_credential_ref",
    "named_credential_refs",
    "normalize_connection_build",
    "register_credential_resolver",
    "release_cost",
    "settle_cost",
]
