"""Versioned chat-storage models — events, parts, manifest.

Every model inherits from `VersionedChatModel` (which inherits from
`alkera_core.versioning.VersionedModel`); `alkera_core/versioning/README.md`
holds the evolution rules.

When evolving any model in this package: bump `SCHEMA_VERSION` and add
a fresh fixture under `packages/api-core/tests/fixtures/chat/v<X.Y.Z>/`
— the auto-discovering lineage tests in
`packages/api-core/tests/schemas/chat/` will
load every historical fixture with the current reader and assert no
exceptions.
"""

from __future__ import annotations

from alkera_core.schemas.chat.base import VersionedChatModel
from alkera_core.schemas.chat.events import (
    NON_PERSISTED_EVENT_TYPES,
    PROMPT_CANCELLED_FAILED,
    PROMPT_CANCELLED_NO_SLOT,
    PROMPT_CANCELLED_NOT_TAKEN,
    PROMPT_CANCELLED_STOPPED,
    STANDING_OPTIONS,
    AgentMessageChunk,
    AgentThoughtChunk,
    AvailableCommandsUpdate,
    CanonicalPermissionKind,
    CommandExecuted,
    CommandResult,
    CompactionApplied,
    ConversationCleared,
    Event,
    EventBase,
    FileEdited,
    Heartbeat,
    LlmCallFinished,
    LlmCallStarted,
    MessageCompleted,
    MessageCreated,
    MessageRole,
    PartCreated,
    PartStarted,
    PartType,
    PartUpdated,
    PermissionOption,
    PermissionOptionId,
    PermissionRequest,
    PermissionResolved,
    PlanUpdated,
    PromptCancelled,
    QuestionAnswered,
    QuestionOption,
    QuestionPrompt,
    QuestionRejected,
    QuestionRequest,
    RateLimited,
    RawEvent,
    Retrying,
    RevertApplied,
    SessionCreated,
    SessionPhase,
    SessionStatus,
    SessionStatusChanged,
    SessionUpdated,
    SubagentCompleted,
    SubagentStarted,
    TombstoneApplied,
    ToolCall,
    ToolCallStatus,
    ToolCallUpdate,
    TurnFinished,
    TurnStarted,
    TurnStopReason,
)
from alkera_core.schemas.chat.manifest import ChatManifest, TokenTotals
from alkera_core.schemas.chat.parts import (
    AgentPart,
    CompactionPart,
    FilePart,
    Part,
    PartBase,
    PatchPart,
    RawPart,
    RawProviderPart,
    ReasoningPart,
    RetryPart,
    SnapshotPart,
    StepFinishPart,
    StepStartPart,
    SubtaskPart,
    TextPart,
    ToolCallPart,
    ToolCallState,
)
from alkera_core.schemas.chat.tasks import Task, TaskList, TaskStatus, TaskValidationError

__all__ = [
    "NON_PERSISTED_EVENT_TYPES",
    "PROMPT_CANCELLED_FAILED",
    "PROMPT_CANCELLED_NOT_TAKEN",
    "PROMPT_CANCELLED_NO_SLOT",
    "PROMPT_CANCELLED_STOPPED",
    "STANDING_OPTIONS",
    # Streaming chunks
    "AgentMessageChunk",
    "AgentPart",
    "AgentThoughtChunk",
    "AvailableCommandsUpdate",
    "CanonicalPermissionKind",
    "ChatManifest",
    "CommandExecuted",
    "CommandResult",
    "CompactionApplied",
    "CompactionPart",
    "ConversationCleared",
    "Event",
    "EventBase",
    "FileEdited",
    "FilePart",
    "Heartbeat",
    "LlmCallFinished",
    "LlmCallStarted",
    "MessageCompleted",
    "MessageCreated",
    "MessageRole",
    "Part",
    "PartBase",
    "PartCreated",
    "PartStarted",
    "PartType",
    "PartUpdated",
    "PatchPart",
    "PermissionOption",
    "PermissionOptionId",
    "PermissionRequest",
    "PermissionResolved",
    "PlanUpdated",
    "PromptCancelled",
    "QuestionAnswered",
    "QuestionOption",
    "QuestionPrompt",
    "QuestionRejected",
    "QuestionRequest",
    "RateLimited",
    "RawEvent",
    "RawPart",
    "RawProviderPart",
    "ReasoningPart",
    "RetryPart",
    "Retrying",
    "RevertApplied",
    "SessionCreated",
    "SessionPhase",
    "SessionStatus",
    "SessionStatusChanged",
    "SessionUpdated",
    "SnapshotPart",
    "StepFinishPart",
    "StepStartPart",
    "SubagentCompleted",
    "SubagentStarted",
    "SubtaskPart",
    "Task",
    "TaskList",
    "TaskStatus",
    "TaskValidationError",
    "TextPart",
    "TokenTotals",
    "TombstoneApplied",
    "ToolCall",
    "ToolCallPart",
    "ToolCallState",
    "ToolCallStatus",
    "ToolCallUpdate",
    "TurnFinished",
    "TurnStarted",
    "TurnStopReason",
    "VersionedChatModel",
]
