"""Chat parts — the leaves of a chat message.

Each `PartBase` subclass is a tagged variant in the `Part` discriminated
union. Unknown tags route to `RawPart` (per the unknown-tag fallback
pattern in `alkera_core.versioning.base.make_unknown_tag_discriminator`)
so an older reader never crashes on a brand-new part type written by a
newer writer.

Each variant
starts at `SCHEMA_VERSION = "1.0.0"` with an empty `MIGRATIONS` ladder.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any, ClassVar, Literal

from pydantic import Discriminator, Field, Tag

from alkera_core.schemas.chat.base import VersionedChatModel
from alkera_core.versioning import make_unknown_tag_discriminator


class PartBase(VersionedChatModel):
    """Shared fields for every part variant.

    Intermediate class — subclasses set `SCHEMA_VERSION` and pin `type`
    to a literal string.
    """

    __abstract__: ClassVar[bool] = True

    part_id: str
    message_id: str
    time: datetime | None = None


# --- text-y parts ---------------------------------------------------------


class TextPart(PartBase):
    SCHEMA_VERSION: ClassVar[str] = "1.0.0"

    type: Literal["text"] = "text"
    text: str = ""
    synthetic: bool = False
    """True if this part was generated by tooling rather than the model
    (e.g. an inserted system message). Lets UI render distinctly."""
    ignored: bool = False
    """Hint to UI/replay to skip rendering this part."""
    redacted: bool = False
    """True if `text` was swapped for a placeholder by a PII/secrets
    redactor. The original content is gone — only `redacted=True` and a
    placeholder string remain."""


class ReasoningPart(PartBase):
    """Provider-private 'thinking' content (Anthropic extended thinking,
    OpenAI o1 reasoning). `signature`/`encrypted` carry Anthropic's
    redacted-thinking opaque blobs."""

    SCHEMA_VERSION: ClassVar[str] = "1.0.0"

    type: Literal["reasoning"] = "reasoning"
    text: str = ""
    signature: str | None = None
    encrypted: bool = False


# --- file / attachment ---------------------------------------------------


class FilePart(PartBase):
    """A file attached to the message. The bytes live in the global
    blob store at `<.alkera>/blobs/<ab>/<cd>/<sha256>`; this part just
    carries the reference + display metadata."""

    # 1.1.0: ``node_id`` (additive), and ``sha256`` gains a default so a part
    #        that names a Files node whose content digest is not known yet is
    #        still a valid part.
    SCHEMA_VERSION: ClassVar[str] = "1.1.0"

    type: Literal["file"] = "file"
    sha256: str = ""
    filename: str = ""
    mime: str = "application/octet-stream"
    size: int = 0
    source: Literal["file", "symbol", "resource", "external"] | None = None
    #: The Files node this part refers to, when the file came from the Files
    #: tree rather than the blob store. Naming it here grants nothing: the box
    #: fetches the bytes through the content API, which decides per request.
    node_id: str | None = None


# --- tool calls ----------------------------------------------------------


ToolCallState = Literal["pending", "running", "completed", "error"]


class ToolCallPart(PartBase):
    """Tool invocation. Goes through the lifecycle
    pending → running → completed/error via `part.updated` events
    (see `events.PartUpdated`).
    """

    SCHEMA_VERSION: ClassVar[str] = "1.0.0"

    type: Literal["tool_call"] = "tool_call"
    call_id: str
    name: str = ""
    input: dict[str, Any] = Field(default_factory=dict)
    state: ToolCallState = "pending"
    output: dict[str, Any] | str | None = None
    error_text: str | None = None
    attachments: list[str] = Field(default_factory=list)
    """List of blob sha256s the tool produced (e.g. screenshots)."""


# --- step + snapshot ------------------------------------------------------


class StepStartPart(PartBase):
    SCHEMA_VERSION: ClassVar[str] = "1.0.0"

    type: Literal["step_start"] = "step_start"
    snapshot: str | None = None
    """Optional VCS snapshot hash captured at the start of this step."""


class StepFinishPart(PartBase):
    SCHEMA_VERSION: ClassVar[str] = "1.0.0"

    type: Literal["step_finish"] = "step_finish"
    reason: str = ""
    tokens: dict[str, int] = Field(default_factory=dict)
    cost: float | None = None
    snapshot: str | None = None


class SnapshotPart(PartBase):
    """Standalone VCS snapshot marker (not tied to a step boundary)."""

    SCHEMA_VERSION: ClassVar[str] = "1.0.0"

    type: Literal["snapshot"] = "snapshot"
    snapshot_hash: str


class PatchPart(PartBase):
    """Patch produced by a code-editing turn. `files` records the paths
    touched + their per-file hashes."""

    SCHEMA_VERSION: ClassVar[str] = "1.0.0"

    type: Literal["patch"] = "patch"
    hash: str
    files: list[str] = Field(default_factory=list)


# --- multi-agent / subagent ----------------------------------------------


class AgentPart(PartBase):
    """Marker for a switch to a sub-agent."""

    SCHEMA_VERSION: ClassVar[str] = "1.0.0"

    type: Literal["agent"] = "agent"
    name: str = ""
    source: Literal["file", "external", "builtin"] | None = None


class SubtaskPart(PartBase):
    """A discrete subtask handed off to another agent. The harness
    typically follows up with a fresh `MessageCreated` / `PartCreated`
    sequence under a new `agent_session_id`."""

    SCHEMA_VERSION: ClassVar[str] = "1.0.0"

    type: Literal["subtask"] = "subtask"
    prompt: str = ""
    description: str | None = None
    agent: str = ""
    model: str | None = None
    command: str | None = None


# --- meta -----------------------------------------------------------------


class CompactionPart(PartBase):
    """Marker that this point is a compaction boundary. The actual
    elided messages get a separate `CompactionApplied` event with the
    summary text."""

    SCHEMA_VERSION: ClassVar[str] = "1.0.0"

    type: Literal["compaction"] = "compaction"
    auto: bool = False
    """True if compaction was triggered by context-overflow rather than
    an explicit user/harness request."""
    overflow: bool = False


class RetryPart(PartBase):
    SCHEMA_VERSION: ClassVar[str] = "1.0.0"

    type: Literal["retry"] = "retry"
    attempt: int = 1
    error: str = ""


# --- escape hatch ---------------------------------------------------------


class RawProviderPart(PartBase):
    """Raw provider payload we don't model yet.

    Distinct from `RawPart` (the fallback for unknown discriminator
    tags): `RawProviderPart` is *intentionally* used when a writer
    wants to persist a provider blob it can't translate into a typed
    variant. The `type` field is the literal `"raw_provider"` —
    discoverable in the union, not a tag fallback.
    """

    SCHEMA_VERSION: ClassVar[str] = "1.0.0"

    type: Literal["raw_provider"] = "raw_provider"
    provider_id: str = ""
    payload: dict[str, Any] = Field(default_factory=dict)


# --- catch-all fallback for UNKNOWN tags ---------------------------------


class RawPart(PartBase):
    """Fallback for unknown discriminator tags.

    When a newer writer adds e.g. `type="screen_recording"` and our
    reader doesn't know that variant, the discriminator routes it here
    so the payload survives the load + a future re-dump intact.

    `type` carries the unknown tag verbatim so it round-trips. The
    extras the unknown variant brought along ride on `__pydantic_extra__`
    (via `extra="allow"`) — they don't need to be enumerated here.
    """

    SCHEMA_VERSION: ClassVar[str] = "1.0.0"

    type: str = "unknown"


# --- discriminated union --------------------------------------------------

_KNOWN_PART_TAGS: set[str] = {
    "text",
    "reasoning",
    "file",
    "tool_call",
    "step_start",
    "step_finish",
    "snapshot",
    "patch",
    "agent",
    "subtask",
    "compaction",
    "retry",
    "raw_provider",
}

#: Every part kind this build knows, for a surface that must decide what each
#: one becomes (a Slack thread, an export) and prove it decided for all of them.
KNOWN_PART_TAGS: frozenset[str] = frozenset(_KNOWN_PART_TAGS)

_part_tag = make_unknown_tag_discriminator(_KNOWN_PART_TAGS)

Part = Annotated[
    (
        Annotated[TextPart, Tag("text")]
        | Annotated[ReasoningPart, Tag("reasoning")]
        | Annotated[FilePart, Tag("file")]
        | Annotated[ToolCallPart, Tag("tool_call")]
        | Annotated[StepStartPart, Tag("step_start")]
        | Annotated[StepFinishPart, Tag("step_finish")]
        | Annotated[SnapshotPart, Tag("snapshot")]
        | Annotated[PatchPart, Tag("patch")]
        | Annotated[AgentPart, Tag("agent")]
        | Annotated[SubtaskPart, Tag("subtask")]
        | Annotated[CompactionPart, Tag("compaction")]
        | Annotated[RetryPart, Tag("retry")]
        | Annotated[RawProviderPart, Tag("raw_provider")]
        | Annotated[RawPart, Tag("__unknown__")]
    ),
    Discriminator(_part_tag),
]
"""Discriminated union over every known Part variant + an unknown-tag
fallback. Use with `TypeAdapter(Part).validate_python(d)`."""


__all__ = [
    "KNOWN_PART_TAGS",
    "AgentPart",
    "CompactionPart",
    "FilePart",
    "Part",
    "PartBase",
    "PatchPart",
    "RawPart",
    "RawProviderPart",
    "ReasoningPart",
    "RetryPart",
    "SnapshotPart",
    "StepFinishPart",
    "StepStartPart",
    "SubtaskPart",
    "TextPart",
    "ToolCallPart",
    "ToolCallState",
]
